from typing import Tuple, Set, Iterable, List


class IAssemblyRestrictedObject:
    def Editable(self) -> bool: ...


class Notification:
    @overload
    def __init__(self, allowedAssemblies: Iterable[Assembly]): ...
    @overload
    def __init__(self): ...
    @property
    def DateUpdated(self) -> DateTime: ...
    @property
    def AllowedAssemblies(self) -> ICollection: ...
    @property
    def MetadataCopy(self) -> IDictionary: ...
    @property
    def ButtonClicked(self) -> Action: ...
    @ButtonClicked.setter
    def ButtonClicked(self, value: Action) -> None: ...
    @property
    def Item(self, key: str) -> str: ...
    @Item.setter
    def Item(self, key: str, value: str) -> None: ...
    @property
    def Title(self) -> str: ...
    @Title.setter
    def Title(self, value: str) -> None: ...
    @property
    def Description(self) -> str: ...
    @Description.setter
    def Description(self, value: str) -> None: ...
    @property
    def Message(self) -> str: ...
    @Message.setter
    def Message(self, value: str) -> None: ...
    @property
    def SeverityLevel(self) -> Severity: ...
    @SeverityLevel.setter
    def SeverityLevel(self, value: Severity) -> None: ...
    @property
    def CancelButtonTitle(self) -> str: ...
    @CancelButtonTitle.setter
    def CancelButtonTitle(self, value: str) -> None: ...
    @property
    def ConfirmButtonTitle(self) -> str: ...
    @ConfirmButtonTitle.setter
    def ConfirmButtonTitle(self, value: str) -> None: ...
    @property
    def AlternateButtonTitle(self) -> str: ...
    @AlternateButtonTitle.setter
    def AlternateButtonTitle(self, value: str) -> None: ...
    @property
    def ShowEventId(self) -> Nullable: ...
    @overload
    def ExecuteAssemblyProtectedCode(action: Action) -> None: ...
    @overload
    def ExecuteAssemblyProtectedCode(func: Func) -> TResult: ...
    def ShowModal(self) -> None: ...
    def HideModal(self) -> None: ...
    def RemoveMetadata(self, key: str) -> bool: ...
    def ToString(self) -> str: ...
    def Editable(self) -> bool: ...
    def add_PropertyChanged(self, value: PropertyChangedEventHandler) -> None: ...
    def remove_PropertyChanged(self, value: PropertyChangedEventHandler) -> None: ...


class ButtonType:
    CancelOrClose = 0
    Confirm = 1
    Alternate = 2


class NotificationButtonClickedArgs:
    def __init__(self, notification: Notification, buttonClicked: ButtonType): ...
    @property
    def Notification(self) -> Notification: ...
    @property
    def ButtonClicked(self) -> ButtonType: ...


class NotificationCenter:




class Severity:
    Debug = 0
    Info = 1
    Warning = 2
    Serious = 3
    Critical = 4
