from typing import Tuple, Set, Iterable, List, overload


class WorldMapDayNight:
    def __init__(self): ...
    def Dispose(self) -> None: ...
    def HasMapForCurrentSettings(self) -> bool: ...
    def LocationToMap(self, latlong: Point2d) -> Point: ...
    def MakeMapBitmap(self) -> None: ...
    def Map(self) -> Image: ...
    def MapToLocation(self, mapPoint: Point) -> Point2d: ...
    def SetDayNightDisplay(self, bOn: bool) -> None: ...
    def SetEnabled(self, bEnabled: bool) -> None: ...
    def SetTimeInfo(self, dt: DateTime, timezone: float, daylightSavingMinutes: int, bDaylightSavingsOn: bool) -> None: ...
