from typing import Tuple, Set, Iterable, List


class IUserInterfaceSection:
    @property
    def Hidden(self) -> bool: ...
    def OnUserInterfaceSectionExpanding(self, userInterfaceSection: UserInterfaceSection, expanding: bool) -> None: ...
    def UserInterfaceDisplayData(self, userInterfaceSection: UserInterfaceSection, renderContentList: Set(RenderContent)) -> None: ...


class UserInterfaceSection:
    def Expand(self, expand: bool) -> None: ...
    def FromWindow(window: Object) -> UserInterfaceSection: ...
    @property
    def RenderContent(self) -> RenderContent: ...
    @property
    def Window(self) -> Object: ...
    def GetContentList(self) -> Set(RenderContent): ...
    def Show(self, visible: bool) -> None: ...


class WorldMapDayNight:
    def __init__(self): ...
    def Dispose(self) -> None: ...
    def HasMapForCurrentSettings(self) -> bool: ...
    def LocationToMap(self, latlong: Point2d) -> Point: ...
    def MakeMapBitmap(self) -> None: ...
    def Map(self) -> Image: ...
    def MapToLocation(self, mapPoint: Point) -> Point2d: ...
    def SetDayNightDisplay(self, bOn: bool) -> None: ...
    def SetEnabled(self, bEnabled: bool) -> None: ...
    def SetTimeInfo(self, dt: DateTime, timezone: float, daylightSavingMinutes: int, bDaylightSavingsOn: bool) -> None: ...
