from typing import Tuple, Set, Iterable, List


class GH_NetworkSorter:
    def __init__(self): ...
    def CreateNodeList(self, objs: List) -> None: ...
    def CreateContext(self, objs: List) -> None: ...
    def Sort(self, bDamp: Single, bLimit: Single) -> None: ...


class GH_NetworkSorterNode:
    def __init__(self, obj_target: IGH_DocumentObject): ...
    def ConstructLinkForces(self) -> None: ...
    def ConstructNodeForces(self, objs: List) -> None: ...
    def AdjustTarget(self, bDamp: Single, bLimit: Single) -> None: ...
