from typing import Tuple, Set, Iterable, List


class ProviderIds:
    def __init__(self): ...
    @property
    def Sun() -> Guid: ...
    @property
    def CurrentEnvironment() -> Guid: ...
    @property
    def RhinoSettings() -> Guid: ...
    @property
    def Dithering() -> Guid: ...
    @property
    def LinearWorkflow() -> Guid: ...
    @property
    def Skylight() -> Guid: ...
    @property
    def GroundPlane() -> Guid: ...
    @property
    def UndoRecord() -> Guid: ...
    @property
    def Undo() -> Guid: ...
    @property
    def ContentLookup() -> Guid: ...
    @property
    def ContentDisplayCollection() -> Guid: ...
    @property
    def ContentDatabase() -> Guid: ...
    @property
    def ContentSelection() -> Guid: ...
    @property
    def ContentPreviewRendered() -> Guid: ...
    @property
    def ImageFileInfo() -> Guid: ...
    @property
    def ContentParam() -> Guid: ...
    @property
    def NamedItem() -> Guid: ...
    @property
    def PreviewSettings() -> Guid: ...
    @property
    def ContentEditorSettings() -> Guid: ...
    @property
    def ContentUpdatePreviewMarkersEventInfo() -> Guid: ...
    @property
    def NewContentControlAssignBy() -> Guid: ...
    @property
    def ContentUIs() -> Guid: ...
    @property
    def SelectionNavigator() -> Guid: ...
    @property
    def ContentChildSlot() -> Guid: ...
    @property
    def Decals() -> Guid: ...
    @property
    def RdkEdit() -> Guid: ...
    @property
    def NullGuid() -> Guid: ...
    @property
    def RdkRendering() -> Guid: ...
    @property
    def RdkRenderingProgress() -> Guid: ...
    @property
    def RdkRenderingGamma() -> Guid: ...
    @property
    def RdkRenderingToneMapping() -> Guid: ...
    @property
    def RdkRenderingPostEffects() -> Guid: ...
    @property
    def RdkRenderingPostEffectDOF() -> Guid: ...
    @property
    def RdkRenderingPostEffectFog() -> Guid: ...
    @property
    def RdkRenderingPostEffectGlare() -> Guid: ...
    @property
    def RdkRenderingPostEffectGlow() -> Guid: ...


class EventInfoArgs:
    @property
    def DataType(self) -> Guid: ...
    @property
    def EventInfoPtr(self) -> IntPtr: ...


class EventArgs:
    @property
    def DataType(self) -> Guid: ...
