from typing import Tuple, Set, Iterable, List


class IRhRdkContentThumbnail:
    def ChildContent(self) -> RenderContent: ...
    def GroupId(self) -> Guid: ...
    def TopLevelContent(self) -> RenderContent: ...


class IRhRdkContentThumbnailList_Sizes:
    Tiny = 0
    Small = 1
    Medium = 2
    Large = 3
    Custom = 4


class IRhRdkThumbnail:
    def Dib(self, dibOut: Bitmap) -> Tuple[Bitmap]: ...
    def GetDib(self) -> Bitmap: ...
    def GetDisplayRect(self, rectOut: RectangleF) -> Tuple[RectangleF]: ...
    def Id(self) -> Guid: ...
    def IsHot(self) -> bool: ...
    def IsSelected(self) -> bool: ...
    def Label(self) -> str: ...


class IRhRdkThumbnailList:
    def Add(self, t: Thumbnail) -> None: ...
    def Clear(self) -> None: ...
    def Get(self, u: Guid) -> Tuple[IRhRdkThumbnail, Guid]: ...
    def GetGridMetrics(self, w: int, h: int, ox: int, oy: int) -> Tuple[int, int, int, int]: ...
    def GetSize(self) -> IRhRdkContentThumbnailList_Sizes: ...
    def GetStatisticsHeaderHeight(self) -> None: ...
    def Mode(self) -> IRhRdkThumbnailList_Modes: ...
    def SetClientText(self, w: str) -> None: ...
    def SetCustomBitmapSize(self, w: int, h: int) -> None: ...
    def SetMode(self, m: IRhRdkThumbnailList_Modes, b: bool) -> None: ...
    def SetShowLabels(self, b: bool) -> None: ...
    def Shape(self) -> IRhRdkThumbnailList_Shapes: ...
    def ShowLabels(self) -> bool: ...
    def UUID(self) -> Guid: ...


class IRhRdkThumbnailList_Modes:
    Grid = 0
    List = 1
    Tree = 2


class IRhRdkThumbnailList_Shapes:
    Square = 0
    Wide = 1


class ThumbData:
    def __init__(self): ...
    def add_PropertyChanged(self, value: PropertyChangedEventHandler) -> None: ...
    @property
    def Children(self) -> List: ...
    @property
    def Content(self) -> RenderContent: ...
    @property
    def Id(self) -> Guid: ...
    @property
    def Image(self) -> Bitmap: ...
    @property
    def Intensity(self) -> str: ...
    @property
    def InUse(self) -> bool: ...
    @property
    def InUseColor(self) -> List: ...
    @property
    def Name(self) -> str: ...
    @property
    def Parent(self) -> ThumbData: ...
    @property
    def PreviewAppearance(self) -> PreviewAppearance: ...
    @property
    def Selected(self) -> bool: ...
    @property
    def Tags(self) -> List: ...
    @property
    def TopLevel(self) -> bool: ...
    @property
    def Type(self) -> str: ...
    def GetPreviewHeigth(thumb_size: Sizes, shape: Shapes) -> int: ...
    def GetPreviewWidth(thumb_size: Sizes, shape: Shapes) -> int: ...
    def remove_PropertyChanged(self, value: PropertyChangedEventHandler) -> None: ...
    @Children.setter
    def Children(self, value: List) -> None: ...
    @Content.setter
    def Content(self, value: RenderContent) -> None: ...
    @Id.setter
    def Id(self, value: Guid) -> None: ...
    @Image.setter
    def Image(self, value: Bitmap) -> None: ...
    @Intensity.setter
    def Intensity(self, value: str) -> None: ...
    @InUse.setter
    def InUse(self, value: bool) -> None: ...
    @InUseColor.setter
    def InUseColor(self, value: List) -> None: ...
    @Name.setter
    def Name(self, value: str) -> None: ...
    @Parent.setter
    def Parent(self, value: ThumbData) -> None: ...
    @PreviewAppearance.setter
    def PreviewAppearance(self, value: PreviewAppearance) -> None: ...
    @Selected.setter
    def Selected(self, value: bool) -> None: ...
    @Tags.setter
    def Tags(self, value: List) -> None: ...
    @Type.setter
    def Type(self, value: str) -> None: ...


class Thumbnail:
    def __init__(self, pRdkThumbnail: IntPtr): ...
    def Dib(self, dibOut: Bitmap) -> Tuple[Bitmap]: ...
    def Dispose(self) -> None: ...
    @property
    def CppPointer(self) -> IntPtr: ...
    def GetDib(self) -> Bitmap: ...
    def GetDisplayRect(self, rectOut: RectangleF) -> Tuple[RectangleF]: ...
    def Id(self) -> Guid: ...
    def IsHot(self) -> bool: ...
    def IsSelected(self) -> bool: ...
    def Label(self) -> str: ...


class ThumbnailViewModelFactory(InternalRdkViewModelFactory):
    def __init__(self): ...
    def Get(self, id: Guid) -> IntPtr: ...
