from typing import Tuple, Set, Iterable, List


class GH_FormattedListItem(GH_SimpleListItem):
    def __init__(self): ...
    def ComputeSize(self, layoutWidth: int) -> Size: ...
    @property
    def Font(self) -> Font: ...
    @property
    def Type(self) -> int: ...
    @property
    def Wrap(self) -> bool: ...
    def RenderItem(self, G: Graphics, destination: Rectangle) -> None: ...
    @Font.setter
    def Font(self, Value: Font) -> None: ...
    @Type.setter
    def Type(self, Value: int) -> None: ...
    @Wrap.setter
    def Wrap(self, Value: bool) -> None: ...


class GH_SimpleListItem:
    def __init__(self): ...
    def ComputeSize(self, layoutWidth: int) -> Size: ...
    @property
    def Alignment(self) -> StringAlignment: ...
    @property
    def BoundingBox(self) -> Rectangle: ...
    @property
    def Colour(self) -> Color: ...
    @property
    def Text(self) -> str: ...
    def RenderItem(self, G: Graphics, destination: Rectangle) -> None: ...
    @Alignment.setter
    def Alignment(self, Value: StringAlignment) -> None: ...
    @BoundingBox.setter
    def BoundingBox(self, Value: Rectangle) -> None: ...
    @Colour.setter
    def Colour(self, Value: Color) -> None: ...
    @Text.setter
    def Text(self, Value: str) -> None: ...




class IGH_ListItem:
    def ComputeSize(self, layoutWidth: int) -> Size: ...
    @property
    def BoundingBox(self) -> Rectangle: ...
    def RenderItem(self, G: Graphics, destination: Rectangle) -> None: ...
    @BoundingBox.setter
    def BoundingBox(self, Value: Rectangle) -> None: ...


