from typing import Tuple, Set, Iterable, List


class IGH_TagArtist:
    @property
    def ID(self) -> Guid: ...
    def Paint(self, canvas: GH_Canvas, channel: GH_CanvasChannel) -> None: ...


class GH_TagArtist:
    @property
    def ID(self) -> Guid: ...
    def Paint(self, canvas: GH_Canvas, channel: GH_CanvasChannel) -> None: ...


class GH_TagArtist_WirePainter(GH_TagArtist):
    def __init__(self, source: IGH_Param, target: IGH_Param, colour: Color, width: int): ...
    @property
    def WirePainter_ID() -> Guid: ...
    def Paint(self, canvas: GH_Canvas, channel: GH_CanvasChannel) -> None: ...
