from typing import Tuple, Set, Iterable, List

class WindowStyle:
    Normal = 0
    Hidden = 1
    Minimized = 2
    Maximized = 3
    NoWindow = -1
class RhinoCore:
    def __init__(self): ...
    def __init__(self, args : Set(str)): ...
    def __init__(self, args : Set(str), windowStyle : WindowStyle): ...
    def __init__(self, args : Set(str), windowStyle : WindowStyle, hostWnd : IntPtr): ...
    def Run (self) -> int: ...
    def OnIdle (self) -> bool: ...
    def Dispose (self) -> None: ...
    def ToString (self) -> str: ...
    def Equals (self, obj : Object) -> bool: ...
    def GetHashCode (self) -> int: ...
    def GetType (self) -> Type: ...
