from typing import Tuple, Set, Iterable, List


class WindowStyle:
    Normal = 0
    Hidden = 1
    Minimized = 2
    Maximized = 3
    NoWindow = -1


class RhinoCore:
    @overload
    def __init__(self): ...
    @overload
    def __init__(self, args: Set(str)): ...
    @overload
    def __init__(self, args: Set(str), windowStyle: WindowStyle): ...
    @overload
    def __init__(self, args: Set(str), windowStyle: WindowStyle, hostWnd: IntPtr): ...
    def Run(self) -> int: ...
    def OnIdle(self) -> bool: ...
    def RaiseIdle(self) -> None: ...
    def DoIdle(self) -> bool: ...
    def DoEvents(self) -> bool: ...
    def Dispose(self) -> None: ...
