from typing import Tuple, Set, Iterable, List


class IGH_IconObjectGrip:
    @property
    def Owner(self) -> IGH_IconObject: ...
    @property
    def Tag(self) -> Object: ...
    @Tag.setter
    def Tag(self, Value: Object) -> None: ...
    @property
    def Index(self) -> int: ...
    @property
    def Position(self) -> PointF: ...
    @Position.setter
    def Position(self, Value: PointF) -> None: ...
    @property
    def Selected(self) -> bool: ...
    @Selected.setter
    def Selected(self, Value: bool) -> None: ...
    def RenderGrip(self, G: Graphics) -> None: ...


class IGH_IconObject:
    @property
    def ObjectID(self) -> Guid: ...
    @property
    def Pivot(self) -> Point: ...
    @Pivot.setter
    def Pivot(self, Value: Point) -> None: ...
    @property
    def Size(self) -> Size: ...
    @Size.setter
    def Size(self, Value: Size) -> None: ...
    @property
    def Image(self) -> Bitmap: ...
    def Contains(self, pt: PointF) -> bool: ...
    def Resize(self, newSize: Size) -> None: ...
    def Grips(self) -> List: ...
    def RenderObject(self, G: Graphics) -> None: ...


class GH_IconObject:
    @property
    def ObjectID(self) -> Guid: ...
    @property
    def Size(self) -> Size: ...
    @Size.setter
    def Size(self, Value: Size) -> None: ...
    @property
    def Pivot(self) -> Point: ...
    @Pivot.setter
    def Pivot(self, Value: Point) -> None: ...
    @property
    def Image(self) -> Bitmap: ...
    def Grips(self) -> List: ...
    def Contains(self, pt: PointF) -> bool: ...
    def Resize(self, newSize: Size) -> None: ...
    def RenderObject(self, G: Graphics) -> None: ...
    def Write(self, writer: GH_IWriter) -> bool: ...
    def Read(self, reader: GH_IReader) -> bool: ...


class GH_IconObject_Rectangle(GH_IconObject):
    def __init__(self): ...
    @property
    def ObjectID(self) -> Guid: ...
    @property
    def Rectangle(self) -> Rectangle: ...
    def RenderObject(self, G: Graphics) -> None: ...
    def Contains(self, pt: PointF) -> bool: ...
    def Write(self, writer: GH_IWriter) -> bool: ...
    def Read(self, reader: GH_IReader) -> bool: ...
