from typing import Tuple, Set, Iterable, List, overload


class Generic:
    @overload
    def __init__(self): ...
    @overload
    def __init__(self, transform: Transform): ...
    def Duplicate(self) -> ITransform: ...
    @property
    def Name(self) -> str: ...
    @property
    def Transform(self) -> Transform: ...
    def Read(self, reader: GH_IReader) -> bool: ...
    def Reverse(self) -> ITransform: ...
    @Transform.setter
    def Transform(self, Value: Transform) -> None: ...
    def ToMatrix(self) -> Transform: ...
    def ToString(self) -> str: ...
    def Write(self, writer: GH_IWriter) -> bool: ...


class Identity:
    def __init__(self): ...
    def Duplicate(self) -> ITransform: ...
    @property
    def Name(self) -> str: ...
    def Read(self, reader: GH_IReader) -> bool: ...
    def Reverse(self) -> ITransform: ...
    def ToMatrix(self) -> Transform: ...
    def ToString(self) -> str: ...
    def Write(self, writer: GH_IWriter) -> bool: ...


class ITransform:
    def Duplicate(self) -> ITransform: ...
    @property
    def Name(self) -> str: ...
    def Reverse(self) -> ITransform: ...
    def ToMatrix(self) -> Transform: ...
    def ToString(self) -> str: ...


class Orientation:
    @overload
    def __init__(self): ...
    @overload
    def __init__(self, source: Plane, target: Plane): ...
    def Duplicate(self) -> ITransform: ...
    @property
    def Name(self) -> str: ...
    @property
    def SourceFrame(self) -> Plane: ...
    @property
    def TargetFrame(self) -> Plane: ...
    def Read(self, reader: GH_IReader) -> bool: ...
    def Reverse(self) -> ITransform: ...
    @SourceFrame.setter
    def SourceFrame(self, Value: Plane) -> None: ...
    @TargetFrame.setter
    def TargetFrame(self, Value: Plane) -> None: ...
    def ToMatrix(self) -> Transform: ...
    def ToString(self) -> str: ...
    def Write(self, writer: GH_IWriter) -> bool: ...


class Projection:
    @overload
    def __init__(self): ...
    @overload
    def __init__(self, plane: Plane): ...
    def Duplicate(self) -> ITransform: ...
    @property
    def Name(self) -> str: ...
    @property
    def ProjectionPlane(self) -> Plane: ...
    def Read(self, reader: GH_IReader) -> bool: ...
    def Reverse(self) -> ITransform: ...
    @ProjectionPlane.setter
    def ProjectionPlane(self, Value: Plane) -> None: ...
    def ToMatrix(self) -> Transform: ...
    def ToString(self) -> str: ...
    def Write(self, writer: GH_IWriter) -> bool: ...


class Rotation:
    @overload
    def __init__(self): ...
    @overload
    def __init__(self, center: Point3d, axis: Vector3d, angle: float): ...
    @overload
    def __init__(self, center: Point3d, dir0: Vector3d, dir1: Vector3d): ...
    def Duplicate(self) -> ITransform: ...
    @property
    def Name(self) -> str: ...
    @property
    def RotationAngle(self) -> float: ...
    @property
    def RotationAxis(self) -> Vector3d: ...
    @property
    def RotationCenter(self) -> Point3d: ...
    def Read(self, reader: GH_IReader) -> bool: ...
    def Reverse(self) -> ITransform: ...
    @RotationAngle.setter
    def RotationAngle(self, Value: float) -> None: ...
    @RotationAxis.setter
    def RotationAxis(self, Value: Vector3d) -> None: ...
    @RotationCenter.setter
    def RotationCenter(self, Value: Point3d) -> None: ...
    def ToMatrix(self) -> Transform: ...
    def ToString(self) -> str: ...
    def Write(self, writer: GH_IWriter) -> bool: ...


class Scale:
    @overload
    def __init__(self): ...
    @overload
    def __init__(self, point: Point3d, scale: float): ...
    @overload
    def __init__(self, frame: Plane, scale: float): ...
    @overload
    def __init__(self, frame: Plane, xscale: float, yscale: float, zscale: float): ...
    def Duplicate(self) -> ITransform: ...
    @property
    def Name(self) -> str: ...
    @property
    def ScaleXFactor(self) -> float: ...
    @property
    def ScaleYFactor(self) -> float: ...
    @property
    def ScaleZFactor(self) -> float: ...
    @property
    def ScalingFrame(self) -> Plane: ...
    def Read(self, reader: GH_IReader) -> bool: ...
    def Reverse(self) -> ITransform: ...
    @ScaleXFactor.setter
    def ScaleXFactor(self, Value: float) -> None: ...
    @ScaleYFactor.setter
    def ScaleYFactor(self, Value: float) -> None: ...
    @ScaleZFactor.setter
    def ScaleZFactor(self, Value: float) -> None: ...
    @ScalingFrame.setter
    def ScalingFrame(self, Value: Plane) -> None: ...
    def ToMatrix(self) -> Transform: ...
    def ToString(self) -> str: ...
    def Write(self, writer: GH_IWriter) -> bool: ...


class Translation:
    @overload
    def __init__(self): ...
    @overload
    def __init__(self, translation: Vector3d): ...
    def Duplicate(self) -> ITransform: ...
    @property
    def Name(self) -> str: ...
    @property
    def TranslationVector(self) -> Vector3d: ...
    def Read(self, reader: GH_IReader) -> bool: ...
    def Reverse(self) -> ITransform: ...
    @TranslationVector.setter
    def TranslationVector(self, Value: Vector3d) -> None: ...
    def ToMatrix(self) -> Transform: ...
    def ToString(self) -> str: ...
    def Write(self, writer: GH_IWriter) -> bool: ...
