from typing import Tuple, Set, Iterable, List


class Dithering(DocumentOrFreeFloatingBase):
    @overload
    def __init__(self): ...
    @overload
    def __init__(self, d: Dithering): ...
    def CopyFrom(self, src: FreeFloatingBase) -> None: ...
    @property
    def Method(self) -> Methods: ...
    @Method.setter
    def Method(self, value: Methods) -> None: ...


class RenderSettings(CommonObject):
    @overload
    def __init__(self, source: RenderSettings): ...
    @overload
    def __init__(self): ...
    @property
    def AmbientLight(self) -> Color: ...
    @AmbientLight.setter
    def AmbientLight(self, value: Color) -> None: ...
    @property
    def BackgroundColorTop(self) -> Color: ...
    @BackgroundColorTop.setter
    def BackgroundColorTop(self, value: Color) -> None: ...
    @property
    def BackgroundColorBottom(self) -> Color: ...
    @BackgroundColorBottom.setter
    def BackgroundColorBottom(self, value: Color) -> None: ...
    @property
    def UseHiddenLights(self) -> bool: ...
    @UseHiddenLights.setter
    def UseHiddenLights(self, value: bool) -> None: ...
    @property
    def DepthCue(self) -> bool: ...
    @DepthCue.setter
    def DepthCue(self, value: bool) -> None: ...
    @property
    def FlatShade(self) -> bool: ...
    @FlatShade.setter
    def FlatShade(self, value: bool) -> None: ...
    @property
    def RenderBackfaces(self) -> bool: ...
    @RenderBackfaces.setter
    def RenderBackfaces(self, value: bool) -> None: ...
    @property
    def RenderPoints(self) -> bool: ...
    @RenderPoints.setter
    def RenderPoints(self, value: bool) -> None: ...
    @property
    def RenderCurves(self) -> bool: ...
    @RenderCurves.setter
    def RenderCurves(self, value: bool) -> None: ...
    @property
    def RenderIsoparams(self) -> bool: ...
    @RenderIsoparams.setter
    def RenderIsoparams(self, value: bool) -> None: ...
    @property
    def RenderMeshEdges(self) -> bool: ...
    @RenderMeshEdges.setter
    def RenderMeshEdges(self, value: bool) -> None: ...
    @property
    def RenderAnnotations(self) -> bool: ...
    @RenderAnnotations.setter
    def RenderAnnotations(self, value: bool) -> None: ...
    @property
    def AntialiasLevel(self) -> AntialiasLevel: ...
    @AntialiasLevel.setter
    def AntialiasLevel(self, value: AntialiasLevel) -> None: ...
    @property
    def UseViewportSize(self) -> bool: ...
    @UseViewportSize.setter
    def UseViewportSize(self, value: bool) -> None: ...
    @property
    def ScaleBackgroundToFit(self) -> bool: ...
    @ScaleBackgroundToFit.setter
    def ScaleBackgroundToFit(self, value: bool) -> None: ...
    @property
    def TransparentBackground(self) -> bool: ...
    @TransparentBackground.setter
    def TransparentBackground(self, value: bool) -> None: ...
    @property
    def ImageUnitSystem(self) -> UnitSystem: ...
    @ImageUnitSystem.setter
    def ImageUnitSystem(self, value: UnitSystem) -> None: ...
    @property
    def ImageDpi(self) -> float: ...
    @ImageDpi.setter
    def ImageDpi(self, value: float) -> None: ...
    @property
    def ImageSize(self) -> Size: ...
    @ImageSize.setter
    def ImageSize(self, value: Size) -> None: ...
    @property
    def ShadowmapLevel(self) -> int: ...
    @ShadowmapLevel.setter
    def ShadowmapLevel(self, value: int) -> None: ...
    @property
    def BackgroundStyle(self) -> BackgroundStyle: ...
    @BackgroundStyle.setter
    def BackgroundStyle(self, value: BackgroundStyle) -> None: ...
    @property
    def LinearWorkflow(self) -> LinearWorkflow: ...
    @property
    def Dithering(self) -> Dithering: ...
    @NamedView.setter
    def NamedView(self, value: str) -> None: ...
    @property
    def NamedView(self) -> str: ...
    @Snapshot.setter
    def Snapshot(self, value: str) -> None: ...
    @property
    def Snapshot(self) -> str: ...
    @SpecificViewport.setter
    def SpecificViewport(self, value: str) -> None: ...
    @property
    def SpecificViewport(self) -> str: ...
    @property
    def RenderSource(self) -> RenderingSources: ...
    @RenderSource.setter
    def RenderSource(self, value: RenderingSources) -> None: ...


class CachedTextureCoordinates(CommonObject):
    def TryGetAt(self, index: int) -> Tuple[bool, float, float, float]: ...
    @property
    def Dim(self) -> int: ...
    @property
    def MappingId(self) -> Guid: ...
    def Contains(self, item: Point3d) -> bool: ...
    def CopyTo(self, array: Set(Point3d), arrayIndex: int) -> None: ...
    @property
    def Count(self) -> int: ...
    @property
    def IsReadOnly(self) -> bool: ...
    def GetEnumerator(self) -> IEnumerator: ...
    def IndexOf(self, item: Point3d) -> int: ...
    @property
    def Item(self, index: int) -> Point3d: ...


class MappingTag:
    def __init__(self): ...
    @property
    def Id(self) -> Guid: ...
    @Id.setter
    def Id(self, value: Guid) -> None: ...
    @property
    def MappingType(self) -> TextureMappingType: ...
    @MappingType.setter
    def MappingType(self, value: TextureMappingType) -> None: ...
    @property
    def MappingCRC(self) -> UInt32: ...
    @MappingCRC.setter
    def MappingCRC(self, value: UInt32) -> None: ...
    @property
    def MeshTransform(self) -> Transform: ...
    @MeshTransform.setter
    def MeshTransform(self, value: Transform) -> None: ...


class TextureMappingType:
    #None = 0
    SurfaceParameters = 1
    PlaneMapping = 2
    CylinderMapping = 3
    SphereMapping = 4
    BoxMapping = 5
    MeshMappingPrimitive = 6
    SurfaceMappingPrimitive = 7
    BrepMappingPrimitive = 8


class TextureMapping(ModelComponent):
    @property
    def MappingType(self) -> TextureMappingType: ...
    @property
    def Id(self) -> Guid: ...
    @property
    def UvwTransform(self) -> Transform: ...
    @UvwTransform.setter
    def UvwTransform(self, value: Transform) -> None: ...
    @property
    def PrimativeTransform(self) -> Transform: ...
    @PrimativeTransform.setter
    def PrimativeTransform(self, value: Transform) -> None: ...
    @property
    def NormalTransform(self) -> Transform: ...
    @NormalTransform.setter
    def NormalTransform(self, value: Transform) -> None: ...
    @property
    def ComponentType(self) -> ModelComponentType: ...
    @overload
    def Evaluate(self, p: Point3d, n: Vector3d) -> Tuple[int, Point3d]: ...
    @overload
    def Evaluate(self, p: Point3d, n: Vector3d, pXform: Transform, nXform: Transform) -> Tuple[int, Point3d]: ...
    @overload
    def TryGetMappingBox(self) -> Tuple[bool, Plane, Interval, Interval, Interval]: ...
    @overload
    def TryGetMappingBox(self) -> Tuple[bool, Plane, Interval, Interval, Interval, bool]: ...
    def TryGetMappingSphere(self) -> Tuple[bool, Sphere]: ...
    @overload
    def TryGetMappingCylinder(self) -> Tuple[bool, Cylinder]: ...
    @overload
    def TryGetMappingCylinder(self) -> Tuple[bool, Cylinder, bool]: ...
    @overload
    def TryGetMappingPlane(self) -> Tuple[bool, Plane, Interval, Interval, Interval]: ...
    @overload
    def TryGetMappingPlane(self) -> Tuple[bool, Plane, Interval, Interval, Interval, bool]: ...
    def TryGetMappingMesh(self) -> Tuple[bool, Mesh]: ...
    @overload
    def CreatePlaneMapping(plane: Plane, dx: Interval, dy: Interval, dz: Interval) -> TextureMapping: ...
    @overload
    def CreatePlaneMapping(plane: Plane, dx: Interval, dy: Interval, dz: Interval, capped: bool) -> TextureMapping: ...
    def CreateCylinderMapping(cylinder: Cylinder, capped: bool) -> TextureMapping: ...
    def CreateSphereMapping(sphere: Sphere) -> TextureMapping: ...
    def CreateBoxMapping(plane: Plane, dx: Interval, dy: Interval, dz: Interval, capped: bool) -> TextureMapping: ...
    def CreateCustomMeshMapping(mesh: Mesh) -> TextureMapping: ...


class City:
    @property
    def Name(self) -> str: ...
    @property
    def Latitude(self) -> float: ...
    @property
    def Longitude(self) -> float: ...
    @property
    def TimeZone(self) -> float: ...
    def FindNearest(latitude: float, longitude: float) -> City: ...
    def Cities() -> int: ...
    def CityAt(index: int) -> City: ...


class RenderContentSerializer:
    def RegisterSerializer(self, id: Guid) -> bool: ...
    @property
    def FileExtension(self) -> str: ...
    @property
    def ContentType(self) -> RenderContentKind: ...
    @property
    def CanRead(self) -> bool: ...
    @property
    def CanWrite(self) -> bool: ...
    def Read(self, pathToFile: str) -> RenderContent: ...
    def Write(self, pathToFile: str, renderContent: RenderContent, previewArgs: CreatePreviewEventArgs) -> bool: ...
    @property
    def EnglishDescription(self) -> str: ...
    @property
    def LocalDescription(self) -> str: ...


class RenderPropertyChangedEvent:
    @property
    def Document(self) -> RhinoDoc: ...
    @property
    def Context(self) -> int: ...


class GroundPlane(DocumentOrFreeFloatingBase):
    @overload
    def __init__(self): ...
    @overload
    def __init__(self, g: GroundPlane): ...
    def add_Changed(value: EventHandler) -> None: ...
    def remove_Changed(value: EventHandler) -> None: ...
    def CopyFrom(self, src: FreeFloatingBase) -> None: ...
    @property
    def Enabled(self) -> bool: ...
    @Enabled.setter
    def Enabled(self, value: bool) -> None: ...
    @property
    def ShadowOnly(self) -> bool: ...
    @ShadowOnly.setter
    def ShadowOnly(self, value: bool) -> None: ...
    @property
    def AutoAltitude(self) -> bool: ...
    @AutoAltitude.setter
    def AutoAltitude(self, value: bool) -> None: ...
    @property
    def ShowUnderside(self) -> bool: ...
    @ShowUnderside.setter
    def ShowUnderside(self, value: bool) -> None: ...
    @property
    def Altitude(self) -> float: ...
    @Altitude.setter
    def Altitude(self, value: float) -> None: ...
    @property
    def MaterialInstanceId(self) -> Guid: ...
    @MaterialInstanceId.setter
    def MaterialInstanceId(self, value: Guid) -> None: ...
    @property
    def TextureOffset(self) -> Vector2d: ...
    @TextureOffset.setter
    def TextureOffset(self, value: Vector2d) -> None: ...
    @property
    def TextureSize(self) -> Vector2d: ...
    @TextureSize.setter
    def TextureSize(self, value: Vector2d) -> None: ...
    @property
    def TextureRotation(self) -> float: ...
    @TextureRotation.setter
    def TextureRotation(self, value: float) -> None: ...
    @property
    def TextureSizeLocked(self) -> bool: ...
    @TextureSizeLocked.setter
    def TextureSizeLocked(self, value: bool) -> None: ...
    @property
    def TextureOffsetLocked(self) -> bool: ...
    @TextureOffsetLocked.setter
    def TextureOffsetLocked(self, value: bool) -> None: ...


class RenderContentStyles:
    #None = 0
    TextureSummary = 1
    QuickPreview = 2
    PreviewCache = 4
    ProgressivePreview = 8
    LocalTextureMapping = 16
    GraphDisplay = 32
    SharedUI = 64
    Adjustment = 128
    Fields = 256
    ModalEditing = 512
    DynamicFields = 1024


class ContentUuids:
    @property
    def BasicMaterialType() -> Guid: ...
    @property
    def BlendMaterialType() -> Guid: ...
    @property
    def CompositeMaterialType() -> Guid: ...
    @property
    def PlasterMaterialType() -> Guid: ...
    @property
    def MetalMaterialType() -> Guid: ...
    @property
    def PaintMaterialType() -> Guid: ...
    @property
    def PlasticMaterialType() -> Guid: ...
    @property
    def GemMaterialType() -> Guid: ...
    @property
    def GlassMaterialType() -> Guid: ...
    @property
    def PictureMaterialType() -> Guid: ...
    @property
    def DefaultMaterialInstance() -> Guid: ...
    @property
    def RealtimeDisplayMaterialType() -> Guid: ...
    @property
    def BasicEnvironmentType() -> Guid: ...
    @property
    def DefaultEnvironmentInstance() -> Guid: ...
    @property
    def Texture2DCheckerTextureType() -> Guid: ...
    @property
    def Texture3DCheckerTextureType() -> Guid: ...
    @property
    def AdvancedDotTextureType() -> Guid: ...
    @property
    def BitmapTextureType() -> Guid: ...
    @property
    def BlendTextureType() -> Guid: ...
    @property
    def CubeMapTextureType() -> Guid: ...
    @property
    def ExposureTextureType() -> Guid: ...
    @property
    def FBmTextureType() -> Guid: ...
    @property
    def GradientTextureType() -> Guid: ...
    @property
    def GraniteTextureType() -> Guid: ...
    @property
    def GridTextureType() -> Guid: ...
    @property
    def HDRTextureType() -> Guid: ...
    @property
    def EXRTextureType() -> Guid: ...
    @property
    def MarbleTextureType() -> Guid: ...
    @property
    def MaskTextureType() -> Guid: ...
    @property
    def NoiseTextureType() -> Guid: ...
    @property
    def PerlinMarbleTextureType() -> Guid: ...
    @property
    def PerturbingTextureType() -> Guid: ...
    @property
    def ProjectionChangerTextureType() -> Guid: ...
    @property
    def ResampleTextureType() -> Guid: ...
    @property
    def SingleColorTextureType() -> Guid: ...
    @property
    def SimpleBitmapTextureType() -> Guid: ...
    @property
    def StuccoTextureType() -> Guid: ...
    @property
    def TextureAdjustmentTextureType() -> Guid: ...
    @property
    def TileTextureType() -> Guid: ...
    @property
    def TurbulenceTextureType() -> Guid: ...
    @property
    def WavesTextureType() -> Guid: ...
    @property
    def WoodTextureType() -> Guid: ...
    @property
    def HatchBumpTexture() -> Guid: ...
    @property
    def CrossHatchBumpTexture() -> Guid: ...
    @property
    def LeatherBumpTexture() -> Guid: ...
    @property
    def WoodBumpTexture() -> Guid: ...
    @property
    def SpeckleBumpTexture() -> Guid: ...
    @property
    def GritBumpTexture() -> Guid: ...
    @property
    def DotBumpTexture() -> Guid: ...
    @property
    def BasicMaterialCCI() -> Guid: ...
    @property
    def BlendMaterialCCI() -> Guid: ...
    @property
    def CompositeMaterialCCI() -> Guid: ...
    @property
    def BasicEnvironmentCCI() -> Guid: ...


class DynamicIconUsage:
    TreeControl = 0
    SubnodeControl = 1
    ContentControl = 2


class CustomRenderContentAttribute:
    @overload
    def __init__(self, renderEngineGuid: str, imageBased: bool, category: str, is_elevated: bool, is_built_in: bool, is_private: bool): ...
    @overload
    def __init__(self, renderEngineGuid: str, imageBased: bool, category: str, is_elevated: bool, is_built_in: bool, is_private: bool, is_linear: bool, is_hdrcapable: bool, is_normalmap: bool): ...
    @property
    def RenderEngineId(self) -> Guid: ...
    @property
    def ImageBased(self) -> bool: ...
    @ImageBased.setter
    def ImageBased(self, value: bool) -> None: ...
    @property
    def IsLinear(self) -> bool: ...
    @IsLinear.setter
    def IsLinear(self, value: bool) -> None: ...
    @property
    def IsHdrCapable(self) -> bool: ...
    @IsHdrCapable.setter
    def IsHdrCapable(self, value: bool) -> None: ...
    @property
    def IsNormalMap(self) -> bool: ...
    @IsNormalMap.setter
    def IsNormalMap(self, value: bool) -> None: ...
    @property
    def Category(self) -> str: ...
    @Category.setter
    def Category(self, value: str) -> None: ...
    @property
    def IsElevated(self) -> bool: ...
    @IsElevated.setter
    def IsElevated(self, value: bool) -> None: ...
    @property
    def IsBuiltIn(self) -> bool: ...
    @IsBuiltIn.setter
    def IsBuiltIn(self, value: bool) -> None: ...
    @property
    def IsPrivate(self) -> bool: ...
    @IsPrivate.setter
    def IsPrivate(self, value: bool) -> None: ...


class RenderContentKind:
    #None = 0
    Material = 1
    Environment = 2
    Texture = 4


class it_strategy:
    ContentDataBase = 0
    ContentSelection = 1


class ProxyTypes:
    #None = 0
    Single = 1
    Multi = 2


class RenderContentKindList:
    @overload
    def __init__(self): ...
    @overload
    def __init__(self, kind_list: RenderContentKindList): ...
    @overload
    def __init__(self, pRdkRenderContentKindList: IntPtr): ...
    @property
    def CppPointer(self) -> IntPtr: ...
    def Dispose(self) -> None: ...
    def Add(self, kind: RenderContentKind) -> None: ...
    def Count(self) -> int: ...
    def SingleKind(self) -> RenderContentKind: ...
    def Contains(self, kind: RenderContentKind) -> bool: ...


class FilterContentByUsage:
    #None = 0
    Used = 1
    Unused = 2


class RenderContentCollection:
    @overload
    def __init__(self): ...
    @overload
    def __init__(self, nativePtr: IntPtr): ...
    @property
    def CppPointer(self) -> IntPtr: ...
    def Dispose(self) -> None: ...
    def GetFilterContentByUsage(self) -> FilterContentByUsage: ...
    def GetForcedVaries(self) -> bool: ...
    def SetForcedVaries(self, b: bool) -> None: ...
    def SetSearchPattern(self, pattern: str) -> None: ...
    def GetSearchPattern(self) -> str: ...
    def FirstTag(self) -> str: ...
    def NextTag(self) -> str: ...
    def ContentNeedsPreviewThumbnail(self, c: RenderContent) -> bool: ...
    def Remove(self, collection: RenderContentCollection) -> None: ...
    def Add(self, collection: RenderContentCollection) -> None: ...
    def Set(self, collection: RenderContentCollection) -> None: ...
    def Clear(self) -> None: ...
    def Append(self, content: RenderContent) -> None: ...
    def Count(self) -> int: ...
    def Iterator(self) -> ContentCollectionIterator: ...
    def Find_Sel(self, uuid: Guid) -> RenderContent: ...
    def ContentAt(self, index: int) -> RenderContent: ...
    def GetEnumerator(self) -> IEnumerator: ...


class ContentCollectionIterator:
    def __init__(self, pCollection: IntPtr): ...
    @property
    def CppPointer(self) -> IntPtr: ...
    def Dispose(self) -> None: ...
    def DeleteThis(self) -> None: ...
    def First(self) -> RenderContent: ...
    def Next(self) -> RenderContent: ...


class RenderContent:
    def ChildSlotOn(self, childSlotName: str) -> bool: ...
    def SetChildSlotOn(self, childSlotName: str, bOn: bool, cc: ChangeContexts) -> None: ...
    def ChildSlotAmount(self, childSlotName: str) -> float: ...
    def SetChildSlotAmount(self, childSlotName: str, amount: float, cc: ChangeContexts) -> None: ...
    def NewPreviewSceneServer(self, ssd: SceneServerData) -> PreviewSceneServer: ...
    def MatchData(self, oldContent: RenderContent) -> MatchDataResult: ...
    def IsCompatible(self, renderEngineId: Guid) -> bool: ...
    def ChildSlotNameFromParamName(self, paramName: str) -> str: ...
    def ParamNameFromChildSlotName(self, childSlotName: str) -> str: ...
    def FindChild(self, childSlotName: str) -> RenderContent: ...
    @overload
    def SetChild(self, renderContent: RenderContent, childSlotName: str) -> bool: ...
    @overload
    def SetChild(self, renderContent: RenderContent, childSlotName: str, changeContexts: ChangeContexts) -> bool: ...
    @overload
    def AddChild(self, renderContent: RenderContent) -> bool: ...
    @overload
    def AddChild(self, renderContent: RenderContent, childSlotName: str) -> bool: ...
    def DeleteChild(self, childSlotName: str, changeContexts: ChangeContexts) -> bool: ...
    def DeleteAllChildren(self, changeContexts: ChangeContexts) -> None: ...
    def ChangeChild(self, oldContent: RenderContent, newContent: RenderContent) -> bool: ...
    @property
    def ChildSlotName(self) -> str: ...
    @ChildSlotName.setter
    def ChildSlotName(self, value: str) -> None: ...
    def GetEmbeddedFilesList(self) -> Set(str): ...
    def Initialize(self) -> bool: ...
    def Uninitialize(self) -> None: ...
    def Replace(self, newcontent: RenderContent) -> bool: ...
    @overload
    def IsFactoryProductAcceptableAsChild(self, kindId: Guid, factoryKind: str, childSlotName: str) -> bool: ...
    @property
    def FilesToEmbed(self) -> Iterable[str]: ...
    def VirtualIcon(self, size: Size) -> Tuple[bool, Bitmap]: ...
    def Icon(self, size: Size) -> Tuple[bool, Bitmap]: ...
    def DynamicIcon(self, size: Size, usage: DynamicIconUsage) -> Tuple[bool, Bitmap]: ...
    def add_ContentAdded(value: EventHandler) -> None: ...
    def remove_ContentAdded(value: EventHandler) -> None: ...
    def add_ContentRenamed(value: EventHandler) -> None: ...
    def remove_ContentRenamed(value: EventHandler) -> None: ...
    def add_ContentDeleting(value: EventHandler) -> None: ...
    def remove_ContentDeleting(value: EventHandler) -> None: ...
    def add_ContentDeleted(value: EventHandler) -> None: ...
    def remove_ContentDeleted(value: EventHandler) -> None: ...
    def add_ContentReplacing(value: EventHandler) -> None: ...
    def remove_ContentReplacing(value: EventHandler) -> None: ...
    def add_ContentReplaced(value: EventHandler) -> None: ...
    def remove_ContentReplaced(value: EventHandler) -> None: ...
    def add_ContentChanged(value: EventHandler) -> None: ...
    def remove_ContentChanged(value: EventHandler) -> None: ...
    def add_ContentFieldChanged(value: EventHandler) -> None: ...
    def remove_ContentFieldChanged(value: EventHandler) -> None: ...
    def add_ContentUpdatePreview(value: EventHandler) -> None: ...
    def remove_ContentUpdatePreview(value: EventHandler) -> None: ...
    def add_CurrentEnvironmentChanged(value: EventHandler) -> None: ...
    def remove_CurrentEnvironmentChanged(value: EventHandler) -> None: ...
    def Dispose(self) -> None: ...
    @overload
    def Create(type: Guid, flags: ShowContentChooserFlags, doc: RhinoDoc) -> RenderContent: ...
    @overload
    def Create(type: Type, flags: ShowContentChooserFlags, doc: RhinoDoc) -> RenderContent: ...
    @overload
    def Create(type: Guid, parent: RenderContent, childSlotName: str, flags: ShowContentChooserFlags, doc: RhinoDoc) -> RenderContent: ...
    @overload
    def Create(type: Type, parent: RenderContent, childSlotName: str, flags: ShowContentChooserFlags, doc: RhinoDoc) -> RenderContent: ...
    @overload
    def RegisterContent(plugin: PlugIn) -> Set(Type): ...
    @overload
    def RegisterContent(assembly: Assembly, pluginId: Guid) -> Set(Type): ...
    def LoadFromFile(filename: str) -> RenderContent: ...
    @overload
    def AddPersistentRenderContent(renderContent: RenderContent) -> bool: ...
    @overload
    def AddPersistentRenderContent(document: RhinoDoc, renderContent: RenderContent) -> bool: ...
    def FromId(document: RhinoDoc, id: Guid) -> RenderContent: ...
    def MakeCopy(self) -> RenderContent: ...
    @overload
    def FromXml(xml: str) -> RenderContent: ...
    @overload
    def FromXml(xml: str, doc: RhinoDoc) -> RenderContent: ...
    @property
    def Fields(self) -> FieldDictionary: ...
    @property
    def CppPointer(self) -> IntPtr: ...
    @overload
    def BindParameterToField(self, parameterName: str, childSlotName: str, field: Field, setEvent: ChangeContexts) -> None: ...
    @overload
    def BindParameterToField(self, parameterName: str, field: Field, setEvent: ChangeContexts) -> None: ...
    @property
    def TypeName(self) -> str: ...
    @property
    def TypeDescription(self) -> str: ...
    @property
    def Name(self) -> str: ...
    @Name.setter
    def Name(self, value: str) -> None: ...
    @property
    def Notes(self) -> str: ...
    @Notes.setter
    def Notes(self, value: str) -> None: ...
    @property
    def Tags(self) -> str: ...
    @Tags.setter
    def Tags(self, value: str) -> None: ...
    @property
    def Category(self) -> str: ...
    @property
    def Id(self) -> Guid: ...
    @Id.setter
    def Id(self, value: Guid) -> None: ...
    @property
    def TypeId(self) -> Guid: ...
    def ForDisplay(self) -> RenderContent: ...
    def IsReference(self) -> bool: ...
    def UseCount(self) -> int: ...
    def SetRenderHash(self, hash: UInt32) -> None: ...
    def IsRenderHashCached(self) -> bool: ...
    @property
    def RenderHash(self) -> UInt32: ...
    @overload
    def RenderHashExclude(self, flags: TextureRenderHashFlags, excludeParameterNames: str) -> UInt32: ...
    @overload
    def RenderHashExclude(self, flags: CrcRenderHashFlags, excludeParameterNames: str) -> UInt32: ...
    @property
    def TopLevel(self) -> bool: ...
    @property
    def Hidden(self) -> bool: ...
    @Hidden.setter
    def Hidden(self, value: bool) -> None: ...
    @property
    def IsHiddenByAutoDelete(self) -> bool: ...
    @property
    def CanBeEdited(self) -> bool: ...
    @property
    def IsDefaultInstance(self) -> bool: ...
    @property
    def ProxyType(self) -> ProxyTypes: ...
    @property
    def Parent(self) -> RenderContent: ...
    @property
    def FirstChild(self) -> RenderContent: ...
    @property
    def NextSibling(self) -> RenderContent: ...
    @property
    def TopLevelParent(self) -> RenderContent: ...
    @property
    def Document(self) -> RhinoDoc: ...
    @property
    def DocumentRegistered(self) -> RhinoDoc: ...
    @property
    def DocumentAssoc(self) -> RhinoDoc: ...
    @DocumentAssoc.setter
    def DocumentAssoc(self, value: RhinoDoc) -> None: ...
    def OpenInEditor(self) -> bool: ...
    def OpenInModalEditor(self) -> bool: ...
    def Edit(self) -> RenderContent: ...
    @property
    def Xml(self) -> str: ...
    def BeginChange(self, changeContext: ChangeContexts) -> None: ...
    def EndChange(self) -> None: ...
    @overload
    def AddUserInterfaceSection(self, classType: Type, caption: str, createExpanded: bool, createVisible: bool) -> UserInterfaceSection: ...
    def AddAutomaticUserInterfaceSection(self, caption: str, id: int) -> bool: ...
    @overload
    def AddUserInterfaceSection(self, section: ICollapsibleSection) -> bool: ...
    def Factory(self) -> ContentFactory: ...
    def IsContentTypeAcceptableAsChild(self, type: Guid, childSlotName: str) -> bool: ...
    @overload
    def IsFactoryProductAcceptableAsChild(self, factory: ContentFactory, childSlotName: str) -> bool: ...
    def GetParameter(self, parameterName: str) -> Object: ...
    @overload
    def SetParameter(self, parameterName: str, value: Object, changeContext: ChangeContexts) -> bool: ...
    @overload
    def SetParameter(self, parameterName: str, value: Object) -> bool: ...
    @property
    def IsLocked(self) -> bool: ...
    @IsLocked.setter
    def IsLocked(self, value: bool) -> None: ...
    def GetChildSlotParameter(self, parameterName: str, childSlotName: str) -> Object: ...
    def SetChildSlotParameter(self, parameterName: str, childSlotName: str, value: Object, sc: ExtraRequirementsSetContexts) -> bool: ...


class CrcRenderHashFlags:
    Normal = 0
    ExcludeLinearWorkflow = 1
    ExcludeLocalMapping = 2
    Reserved1 = 4
    Reserved2 = 8


class RenderContentEventArgs:
    @property
    def Content(self) -> RenderContent: ...
    @property
    def Document(self) -> RhinoDoc: ...
    @property
    def Reason(self) -> RenderContentChangeReason: ...
    @property
    def EnvironmentUsage(self) -> Usage: ...


class RenderContentChangedEventArgs(RenderContentEventArgs):
    @property
    def ChangeContext(self) -> ChangeContexts: ...
    @property
    def OldContent(self) -> RenderContent: ...


class RenderContentChangeReason:
    #None = 0
    Attach = 1
    Detach = 2
    ChangeAttach = 3
    ChangeDetach = 4
    AttachUndo = 5
    DetachUndo = 6
    Open = 7
    Delete = 8


class RenderContentFieldChangedEventArgs(RenderContentChangedEventArgs):
    @property
    def FieldName(self) -> str: ...


class RenderContentType:
    def __init__(self, typeId: Guid): ...
    def GetAllAvailableTypes() -> Set(RenderContentType): ...
    def NewRenderContent(self) -> RenderContent: ...
    @overload
    def NewContentFromTypeId(typeId: Guid) -> RenderContent: ...
    @overload
    def NewContentFromTypeId(typeId: Guid, doc: RhinoDoc) -> RenderContent: ...
    @property
    def Id(self) -> Guid: ...
    @property
    def InternalName(self) -> str: ...
    @property
    def RenderEngineId(self) -> Guid: ...
    @property
    def PlugInId(self) -> Guid: ...
    def Dispose(self) -> None: ...


class RenderMaterialTable:
    def Add(self, c: RenderMaterial) -> bool: ...
    def Remove(self, c: RenderMaterial) -> bool: ...
    def BeginChange(self, changeContext: ChangeContexts) -> None: ...
    def EndChange(self) -> None: ...
    def GetEnumerator(self) -> IEnumerator: ...
    @property
    def Count(self) -> int: ...
    @property
    def Item(self, index: int) -> RenderMaterial: ...


class RenderEnvironmentTable:
    def Add(self, c: RenderEnvironment) -> bool: ...
    def Remove(self, c: RenderEnvironment) -> bool: ...
    def BeginChange(self, changeContext: ChangeContexts) -> None: ...
    def EndChange(self) -> None: ...
    def GetEnumerator(self) -> IEnumerator: ...
    @property
    def Count(self) -> int: ...
    @property
    def Item(self, index: int) -> RenderEnvironment: ...


class RenderTextureTable:
    def Add(self, c: RenderTexture) -> bool: ...
    def Remove(self, c: RenderTexture) -> bool: ...
    def BeginChange(self, changeContext: ChangeContexts) -> None: ...
    def EndChange(self) -> None: ...
    def GetEnumerator(self) -> IEnumerator: ...
    @property
    def Count(self) -> int: ...
    @property
    def Item(self, index: int) -> RenderTexture: ...


class RenderPrimitiveType:
    #None = 0
    Mesh = 1
    Sphere = 2
    Plane = 3
    Box = 4
    Cone = 5


class RenderPrimitiveList:
    def ToMeshArray(self) -> Set(Mesh): ...
    def ToMaterialArray(self) -> Set(RenderMaterial): ...
    @overload
    def Add(self, mesh: Mesh, material: RenderMaterial) -> None: ...
    @overload
    def Add(self, mesh: Mesh, material: RenderMaterial, t: Transform) -> None: ...
    @overload
    def Add(self, sphere: Sphere, material: RenderMaterial) -> None: ...
    @overload
    def Add(self, cone: Cone, truncation: Plane, material: RenderMaterial) -> None: ...
    @overload
    def Add(self, plane: PlaneSurface, material: RenderMaterial) -> None: ...
    @overload
    def Add(self, box: Box, material: RenderMaterial) -> None: ...
    @property
    def UseObjectsMappingChannels(self) -> bool: ...
    @UseObjectsMappingChannels.setter
    def UseObjectsMappingChannels(self, value: bool) -> None: ...
    @property
    def Count(self) -> int: ...
    def PrimitiveType(self, index: int) -> RenderPrimitiveType: ...
    def Mesh(self, index: int) -> Mesh: ...
    def MeshInstance(self, index: int) -> Tuple[Mesh, Transform]: ...
    def TryGetSphere(self, index: int) -> Tuple[bool, Sphere]: ...
    def TryGetBox(self, index: int) -> Tuple[bool, Box]: ...
    def TryGetPlane(self, index: int) -> Tuple[bool, PlaneSurface]: ...
    def TryGetCone(self, index: int) -> Tuple[bool, Cone, Plane]: ...
    def Material(self, index: int) -> RenderMaterial: ...
    @property
    def RhinoObject(self) -> RhinoObject: ...
    def ConvertMeshesToTriangles(self) -> None: ...
    def Clear(self) -> None: ...
    def GetInstanceTransform(self, index: int) -> Transform: ...
    def SetInstanceTransform(self, index: int, xform: Transform) -> None: ...
    def AutoDeleteMeshesOn(self) -> bool: ...
    def AutoDeleteMaterialsOn(self) -> bool: ...
    def Dispose(self) -> None: ...


class CustomRenderMeshProvider:
    @property
    def EdgeSofteningId() -> Guid: ...
    @property
    def DisplacementId() -> Guid: ...
    @property
    def CurvePipingId() -> Guid: ...
    @property
    def ShutLiningId() -> Guid: ...
    @property
    def ThickeningId() -> Guid: ...
    @property
    def Name(self) -> str: ...
    def WillBuildCustomMeshes(self, vp: ViewportInfo, obj: RhinoObject, requestingPlugIn: Guid, preview: bool) -> bool: ...
    def BuildCustomMeshes(self, vp: ViewportInfo, objMeshes: RenderPrimitiveList, requestingPlugIn: Guid, meshType: bool) -> bool: ...
    def RegisterProviders(assembly: Assembly, pluginId: Guid) -> None: ...
    @overload
    def AllObjectsChanged() -> None: ...
    @overload
    def AllObjectsChanged(doc: RhinoDoc) -> None: ...
    def ObjectChanged(doc: RhinoDoc, obj: RhinoObject) -> None: ...
    def DocumentBasedMeshesChanged(doc: RhinoDoc) -> None: ...
    @overload
    def BoundingBox(self, vp: ViewportInfo, obj: RhinoObject, requestingPlugIn: Guid, preview: bool) -> BoundingBox: ...
    @overload
    def BoundingBox(self, vp: ViewportInfo, obj: RhinoObject, doc: RhinoDoc, requestingPlugIn: Guid, attrs: DisplayPipelineAttributes) -> BoundingBox: ...


class CustomRenderMeshProvider2(CustomRenderMeshProvider):
    @overload
    def WillBuildCustomMeshes(self, vp: ViewportInfo, obj: RhinoObject, requestingPlugIn: Guid, preview: bool) -> bool: ...
    @overload
    def BuildCustomMeshes(self, vp: ViewportInfo, objMeshes: RenderPrimitiveList, requestingPlugIn: Guid, preview: bool) -> bool: ...
    @overload
    def BoundingBox(self, vp: ViewportInfo, obj: RhinoObject, requestingPlugIn: Guid, preview: bool) -> BoundingBox: ...
    @overload
    def WillBuildCustomMeshes(self, vp: ViewportInfo, obj: RhinoObject, doc: RhinoDoc, requestingPlugIn: Guid, attrs: DisplayPipelineAttributes) -> bool: ...
    @overload
    def BuildCustomMeshes(self, vp: ViewportInfo, doc: RhinoDoc, objMeshes: RenderPrimitiveList, requestingPlugIn: Guid, attrs: DisplayPipelineAttributes) -> bool: ...
    @overload
    def BoundingBox(self, vp: ViewportInfo, obj: RhinoObject, doc: RhinoDoc, requestingPlugIn: Guid, attrs: DisplayPipelineAttributes) -> BoundingBox: ...


class DecalMapping:
    Planar = 0
    Cylindrical = 1
    Spherical = 2
    UV = 3


class DecalProjection:
    Forward = 0
    Backward = 1
    Both = 2


class Decal:
    @overload
    def Dispose(self) -> None: ...
    @overload
    def Dispose(self, isDisposing: bool) -> None: ...
    def Create(createParams: DecalCreateParams) -> Decal: ...
    @property
    def CRC(self) -> int: ...
    @property
    def TextureInstanceId(self) -> Guid: ...
    @property
    def DecalMapping(self) -> DecalMapping: ...
    @property
    def DecalProjection(self) -> DecalProjection: ...
    @property
    def MapToInside(self) -> bool: ...
    @property
    def Transparency(self) -> float: ...
    @property
    def Origin(self) -> Point3d: ...
    @property
    def VectorUp(self) -> Vector3d: ...
    @property
    def VectorAcross(self) -> Vector3d: ...
    @property
    def Height(self) -> float: ...
    @property
    def Radius(self) -> float: ...
    @property
    def StartLatitude(self) -> float: ...
    @property
    def EndLatitude(self) -> float: ...
    @property
    def StartLongitude(self) -> float: ...
    @property
    def EndLongitude(self) -> float: ...
    def UVBounds(self, minUOut: float, minVOut: float, maxUOut: float, maxVOut: float) -> Tuple[float, float, float, float]: ...
    def CustomData(self) -> List: ...
    def TryGetColor(self, point: Point3d, normal: Vector3d, colInOut: Color4f, uvOut: Point2d) -> Tuple[bool, Color4f, Point2d]: ...
    def ConstPointer(self) -> IntPtr: ...
    def NonConstPointer(self) -> IntPtr: ...


class Decals:
    def Add(self, decal: Decal) -> UInt32: ...
    def Clear(self) -> None: ...
    def Remove(self, decal: Decal) -> bool: ...
    def GetEnumerator(self) -> IEnumerator: ...


class DecalCreateParams:
    def __init__(self): ...
    @property
    def TextureInstanceId(self) -> Guid: ...
    @TextureInstanceId.setter
    def TextureInstanceId(self, value: Guid) -> None: ...
    @property
    def DecalMapping(self) -> DecalMapping: ...
    @DecalMapping.setter
    def DecalMapping(self, value: DecalMapping) -> None: ...
    @property
    def DecalProjection(self) -> DecalProjection: ...
    @DecalProjection.setter
    def DecalProjection(self, value: DecalProjection) -> None: ...
    @property
    def MapToInside(self) -> bool: ...
    @MapToInside.setter
    def MapToInside(self, value: bool) -> None: ...
    @property
    def Transparency(self) -> float: ...
    @Transparency.setter
    def Transparency(self, value: float) -> None: ...
    @property
    def Origin(self) -> Point3d: ...
    @Origin.setter
    def Origin(self, value: Point3d) -> None: ...
    @property
    def VectorUp(self) -> Vector3d: ...
    @VectorUp.setter
    def VectorUp(self, value: Vector3d) -> None: ...
    @property
    def VectorAcross(self) -> Vector3d: ...
    @VectorAcross.setter
    def VectorAcross(self, value: Vector3d) -> None: ...
    @property
    def Height(self) -> float: ...
    @Height.setter
    def Height(self, value: float) -> None: ...
    @property
    def Radius(self) -> float: ...
    @Radius.setter
    def Radius(self, value: float) -> None: ...
    @property
    def StartLatitude(self) -> float: ...
    @StartLatitude.setter
    def StartLatitude(self, value: float) -> None: ...
    @property
    def EndLatitude(self) -> float: ...
    @EndLatitude.setter
    def EndLatitude(self, value: float) -> None: ...
    @property
    def StartLongitude(self) -> float: ...
    @StartLongitude.setter
    def StartLongitude(self, value: float) -> None: ...
    @property
    def EndLongitude(self) -> float: ...
    @EndLongitude.setter
    def EndLongitude(self, value: float) -> None: ...
    @property
    def MinU(self) -> float: ...
    @MinU.setter
    def MinU(self, value: float) -> None: ...
    @property
    def MinV(self) -> float: ...
    @MinV.setter
    def MinV(self, value: float) -> None: ...
    @property
    def MaxU(self) -> float: ...
    @MaxU.setter
    def MaxU(self, value: float) -> None: ...
    @property
    def MaxV(self) -> float: ...
    @MaxV.setter
    def MaxV(self, value: float) -> None: ...


class FreeFloatingBase:
    def CopyFrom(self, src: FreeFloatingBase) -> None: ...


class DocumentOrFreeFloatingBase(FreeFloatingBase):
    def BeginChange(self, cc: ChangeContexts) -> None: ...
    def EndChange(self) -> bool: ...


class ICurrentEnvironment_Get:
    @property
    def ForBackground(self) -> RenderEnvironment: ...
    @property
    def ForBackground_CheckMode(self) -> RenderEnvironment: ...
    @property
    def ForLighting(self) -> RenderEnvironment: ...
    @property
    def ForReflectionAndRefraction(self) -> RenderEnvironment: ...


class ICurrentEnvironment:
    @property
    def ForBackground(self) -> RenderEnvironment: ...
    @ForBackground.setter
    def ForBackground(self, value: RenderEnvironment) -> None: ...
    @property
    def ForBackground_CheckMode(self) -> RenderEnvironment: ...
    @ForBackground_CheckMode.setter
    def ForBackground_CheckMode(self, value: RenderEnvironment) -> None: ...
    @property
    def ForLighting(self) -> RenderEnvironment: ...
    @ForLighting.setter
    def ForLighting(self, value: RenderEnvironment) -> None: ...
    @property
    def ForReflectionAndRefraction(self) -> RenderEnvironment: ...
    @ForReflectionAndRefraction.setter
    def ForReflectionAndRefraction(self, value: RenderEnvironment) -> None: ...
    @ForAnyUsage.setter
    def ForAnyUsage(self, value: RenderEnvironment) -> None: ...


class RenderEnvironment(RenderContent):
    @property
    def CurrentEnvironment() -> RenderEnvironment: ...
    @CurrentEnvironment.setter
    def CurrentEnvironment(value: RenderEnvironment) -> None: ...
    @overload
    def NewBasicEnvironment(environment: SimulatedEnvironment) -> RenderEnvironment: ...
    @overload
    def NewBasicEnvironment(environment: SimulatedEnvironment, doc: RhinoDoc) -> RenderEnvironment: ...
    @overload
    def SimulateEnvironment(self, simulation: SimulatedEnvironment, isForDataOnly: bool) -> Tuple[SimulatedEnvironment]: ...
    @overload
    def SimulateEnvironment(self, isForDataOnly: bool) -> SimulatedEnvironment: ...
    @property
    def TextureChildSlotName(self) -> str: ...


class Utilities:
    def SetDefaultRenderPlugIn(pluginId: Guid) -> bool: ...
    @property
    def DefaultRenderPlugInId() -> Guid: ...
    @property
    def UiFramework() -> UiFrameworks: ...
    @property
    def ShowIncompatibleMaterials() -> bool: ...
    @ShowIncompatibleMaterials.setter
    def ShowIncompatibleMaterials(value: bool) -> None: ...
    @property
    def ShowIncompatibleEnvironments() -> bool: ...
    @ShowIncompatibleEnvironments.setter
    def ShowIncompatibleEnvironments(value: bool) -> None: ...
    @property
    def ShowIncompatibleTextures() -> bool: ...
    @ShowIncompatibleTextures.setter
    def ShowIncompatibleTextures(value: bool) -> None: ...
    def SafeFrameEnabled(doc: RhinoDoc) -> bool: ...
    def ChangeContentType(oldContent: RenderContent, newType: Guid, harvestParameters: bool) -> RenderContent: ...
    def PromptForSaveImageFileParameters(filename: str, width: int, height: int, colorDepth: int) -> Tuple[str, int, int, int]: ...
    def LoadPersistentRenderContentFromFile(docSerialNumber: UInt32, filename: str) -> RenderContent: ...
    @overload
    def FindFile(doc: RhinoDoc, fullPathToFile: str) -> str: ...
    @overload
    def FindFile(doc: RhinoDoc, fullPathToFile: str, unpackFromBitmapTableIfNecessary: bool) -> str: ...
    def IsCachedTextureFileInUse(textureFileName: str) -> bool: ...
    def MoveWindow(hwnd: IntPtr, rect: Rectangle, bRepaint: bool, bRepaintNC: bool) -> None: ...
    def ShowIORMenu(hwnd: IntPtr, pt: Point, outIOR: float, outString: str) -> Tuple[bool, float, str]: ...


class LightManagerSupportClient:
    def __init__(self, doc_uuid: UInt32): ...
    @property
    def CppPointer(self) -> IntPtr: ...
    def Dispose(self) -> None: ...
    def GetLights(self) -> LightArray: ...
    def GetLightFromId(self, uuid: Guid) -> Light: ...
    def OnEditLight(self, lights: LightArray) -> None: ...
    def GroupLights(self, lights: LightArray) -> None: ...
    def UnGroup(self, lights: LightArray) -> None: ...
    def ModifyLight(self, light: Light) -> None: ...
    def DeleteLight(self, light: Light) -> None: ...
    def LightDescription(self, light: Light) -> str: ...
    def ObjectFromLight(self, light: Light) -> RhinoObject: ...
    def SetLightSolo(self, light: Light, bSolo: bool) -> bool: ...
    def GetLightSolo(self, light: Light) -> bool: ...
    def LightsInSoloStorage(self) -> int: ...


class LightArray:
    @overload
    def __init__(self): ...
    @overload
    def __init__(self, pLightArray: IntPtr): ...
    @property
    def CppPointer(self) -> IntPtr: ...
    def Dispose(self) -> None: ...
    def ElementAt(self, index: int) -> Light: ...
    def Append(self, light: Light) -> None: ...
    def Count(self) -> int: ...


class LightMangerSupportCustomEvent:
    light_added = 0
    light_deleted = 1
    light_undeleted = 2
    light_modified = 3
    light_sorted = 4


class LightManagerSupport:
    def RegisterLightManager(plugin: PlugIn) -> None: ...
    def RegisterProviders(assembly: Assembly, pluginId: Guid) -> None: ...
    def PluginId(self) -> Guid: ...
    def RenderEngineId(self) -> Guid: ...
    def ModifyLight(self, doc: RhinoDoc, light: Light) -> None: ...
    def DeleteLight(self, doc: RhinoDoc, light: Light, bUndelete: bool) -> bool: ...
    def GetLights(self, doc: RhinoDoc, light_array: LightArray) -> Tuple[LightArray]: ...
    def LightFromId(self, doc: RhinoDoc, uuid: Guid, light: Light) -> Tuple[bool, Light]: ...
    def ObjectSerialNumberFromLight(self, doc: RhinoDoc, light: Light) -> Tuple[int, Light]: ...
    def OnEditLight(self, doc: RhinoDoc, light_array: LightArray) -> Tuple[bool, LightArray]: ...
    def GroupLights(self, doc: RhinoDoc, light_array: LightArray) -> Tuple[LightArray]: ...
    def UnGroup(self, doc: RhinoDoc, light_array: LightArray) -> Tuple[LightArray]: ...
    def LightDescription(self, doc: RhinoDoc, light: Light) -> Tuple[str, Light]: ...
    def SetLightSolo(self, doc: RhinoDoc, uuid_light: Guid, bSolo: bool) -> bool: ...
    def GetLightSolo(self, doc: RhinoDoc, uuid_light: Guid) -> bool: ...
    def LightsInSoloStorage(self, doc: RhinoDoc) -> int: ...
    def OnCustomLightEvent(self, doc: RhinoDoc, le: LightMangerSupportCustomEvent, light: Light) -> Tuple[Light]: ...


class LinearWorkflow(DocumentOrFreeFloatingBase):
    @overload
    def __init__(self): ...
    @overload
    def __init__(self, src: LinearWorkflow): ...
    def CopyFrom(self, src: FreeFloatingBase) -> None: ...
    @property
    def PreProcessColors(self) -> bool: ...
    @PreProcessColors.setter
    def PreProcessColors(self, value: bool) -> None: ...
    @property
    def PreProcessTextures(self) -> bool: ...
    @PreProcessTextures.setter
    def PreProcessTextures(self, value: bool) -> None: ...
    @property
    def PostProcessFrameBuffer(self) -> bool: ...
    @PostProcessFrameBuffer.setter
    def PostProcessFrameBuffer(self, value: bool) -> None: ...
    @property
    def PreProcessGamma(self) -> Single: ...
    @PreProcessGamma.setter
    def PreProcessGamma(self, value: Single) -> None: ...
    @property
    def PostProcessGamma(self) -> Single: ...
    @PostProcessGamma.setter
    def PostProcessGamma(self, value: Single) -> None: ...
    @property
    def PostProcessGammaReciprocal(self) -> Single: ...
    @property
    def Hash(self) -> UInt32: ...
    def Equals(self, obj: Object) -> bool: ...
    def GetHashCode(self) -> int: ...




class TexturedColor:
    def __init__(self, name: str, value: Color4f, on: bool, amount: Single): ...


class TexturedFloat:
    def __init__(self, name: str, value: Single, on: bool, amount: Single): ...


class RenderMaterial(RenderContent):
    @overload
    def CreateBasicMaterial(material: Material) -> RenderMaterial: ...
    @overload
    def CreateBasicMaterial(material: Material, doc: RhinoDoc) -> RenderMaterial: ...
    def CreateImportedMaterial(material: Material, doc: RhinoDoc, bReference: bool) -> RenderMaterial: ...
    @property
    def PlasterMaterialGuid() -> Guid: ...
    @property
    def PlasticMaterialGuid() -> Guid: ...
    @property
    def PaintMaterialGuid() -> Guid: ...
    @property
    def GlassMaterialGuid() -> Guid: ...
    @property
    def GemMaterialGuid() -> Guid: ...
    @property
    def MetalMaterialGuid() -> Guid: ...
    @property
    def PictureMaterialGuid() -> Guid: ...
    def TextureChildSlotName(self, slot: StandardChildSlots) -> str: ...
    def GetTextureFromUsage(self, which: StandardChildSlots) -> RenderTexture: ...
    def GetTextureOnFromUsage(self, which: StandardChildSlots) -> bool: ...
    def GetTextureAmountFromUsage(self, which: StandardChildSlots) -> float: ...
    @overload
    def SimulateMaterial(self, simulation: Material, isForDataOnly: bool) -> Tuple[Material]: ...
    @overload
    def SimulateMaterial(self, isForDataOnly: bool) -> Material: ...
    def SimulatedMaterial(self, isForDataOnly: bool) -> Material: ...
    def SimulatedPhysicallyBasedMaterial(self, isForDataOnly: bool) -> PhysicallyBasedMaterial: ...
    @property
    def DefaultPreviewGeometryType(self) -> PreviewGeometryType: ...
    @DefaultPreviewGeometryType.setter
    def DefaultPreviewGeometryType(self, value: PreviewGeometryType) -> None: ...
    @property
    def DefaultPreviewBackgroundType(self) -> PreviewBackgroundType: ...
    @DefaultPreviewBackgroundType.setter
    def DefaultPreviewBackgroundType(self, value: PreviewBackgroundType) -> None: ...
    @property
    def DefaultPreviewSize(self) -> float: ...
    @DefaultPreviewSize.setter
    def DefaultPreviewSize(self, value: float) -> None: ...
    @property
    def SmellsLikePlaster(self) -> bool: ...
    @property
    def SmellsLikePaint(self) -> bool: ...
    @property
    def SmellsLikeMetal(self) -> bool: ...
    @property
    def SmellsLikePlastic(self) -> bool: ...
    @property
    def SmellsLikeGem(self) -> bool: ...
    @property
    def SmellsLikeGlass(self) -> bool: ...
    @property
    def SmellsLikeTexturedPlaster(self) -> bool: ...
    @property
    def SmellsLikeTexturedPaint(self) -> bool: ...
    @property
    def SmellsLikeTexturedMetal(self) -> bool: ...
    @property
    def SmellsLikeTexturedPlastic(self) -> bool: ...
    @property
    def SmellsLikeTexturedGem(self) -> bool: ...
    @property
    def SmellsLikeTexturedGlass(self) -> bool: ...
    def HandleTexturedValue(self, slotname: str, tc: TexturedValue) -> bool: ...


class PhysicallyBasedMaterial:
    @property
    def Material(self) -> Material: ...
    def SetTexture(self, texture: Texture, which: TextureType) -> bool: ...
    def GetTexture(self, which: TextureType) -> Texture: ...
    def GetTextures(self) -> Set(Texture): ...
    @property
    def Supported(self) -> bool: ...
    def SynchronizeLegacyMaterial(self) -> None: ...
    @property
    def BaseColor(self) -> Color4f: ...
    @BaseColor.setter
    def BaseColor(self, value: Color4f) -> None: ...
    @property
    def BRDF(self) -> BRDFs: ...
    @BRDF.setter
    def BRDF(self, value: BRDFs) -> None: ...
    @property
    def SubsurfaceScatteringColor(self) -> Color4f: ...
    @SubsurfaceScatteringColor.setter
    def SubsurfaceScatteringColor(self, value: Color4f) -> None: ...
    @property
    def Subsurface(self) -> float: ...
    @Subsurface.setter
    def Subsurface(self, value: float) -> None: ...
    @property
    def SubsurfaceScatteringRadius(self) -> float: ...
    @SubsurfaceScatteringRadius.setter
    def SubsurfaceScatteringRadius(self, value: float) -> None: ...
    @property
    def Metallic(self) -> float: ...
    @Metallic.setter
    def Metallic(self, value: float) -> None: ...
    @property
    def Specular(self) -> float: ...
    @Specular.setter
    def Specular(self, value: float) -> None: ...
    @property
    def ReflectiveIOR(self) -> float: ...
    @ReflectiveIOR.setter
    def ReflectiveIOR(self, value: float) -> None: ...
    @property
    def SpecularTint(self) -> float: ...
    @SpecularTint.setter
    def SpecularTint(self, value: float) -> None: ...
    @property
    def Roughness(self) -> float: ...
    @Roughness.setter
    def Roughness(self, value: float) -> None: ...
    @property
    def Anisotropic(self) -> float: ...
    @Anisotropic.setter
    def Anisotropic(self, value: float) -> None: ...
    @property
    def AnisotropicRotation(self) -> float: ...
    @AnisotropicRotation.setter
    def AnisotropicRotation(self, value: float) -> None: ...
    @property
    def Sheen(self) -> float: ...
    @Sheen.setter
    def Sheen(self, value: float) -> None: ...
    @property
    def SheenTint(self) -> float: ...
    @SheenTint.setter
    def SheenTint(self, value: float) -> None: ...
    @property
    def Clearcoat(self) -> float: ...
    @Clearcoat.setter
    def Clearcoat(self, value: float) -> None: ...
    @property
    def ClearcoatRoughness(self) -> float: ...
    @ClearcoatRoughness.setter
    def ClearcoatRoughness(self, value: float) -> None: ...
    @property
    def OpacityIOR(self) -> float: ...
    @OpacityIOR.setter
    def OpacityIOR(self, value: float) -> None: ...
    @property
    def Opacity(self) -> float: ...
    @Opacity.setter
    def Opacity(self, value: float) -> None: ...
    @property
    def OpacityRoughness(self) -> float: ...
    @OpacityRoughness.setter
    def OpacityRoughness(self, value: float) -> None: ...
    @property
    def Emission(self) -> Color4f: ...
    @Emission.setter
    def Emission(self, value: Color4f) -> None: ...


class IRhRdkPreviewSceneServer_eRotationType:
    Camera = 0
    Object = 1


class PreviewAppearance:
    def __init__(self, pRenderContent: IntPtr): ...
    @property
    def CppPointer(self) -> IntPtr: ...
    @property
    def MetaData(self) -> MetaData: ...
    def Dispose(self) -> None: ...
    def RotationX(self) -> float: ...
    def SetRotationX(self, d: float) -> None: ...
    def RotationY(self) -> float: ...
    def SetRotationY(self, d: float) -> None: ...
    def Size(self) -> float: ...
    def SetSize(self, d: float) -> None: ...
    def RotationType(self) -> IRhRdkPreviewSceneServer_eRotationType: ...
    def SetRotationType(self, type: IRhRdkPreviewSceneServer_eRotationType) -> None: ...
    def Geometry(self) -> PreviewGeometry: ...
    def FromMetaData(self, md: MetaData) -> None: ...
    @overload
    def ToMetaData(self) -> None: ...
    @overload
    def ToMetaData(self, mdp: MetaDataProxy) -> None: ...
    def Background(self) -> PreviewBackground: ...
    def Lighting(self) -> PreviewLighting: ...


class MetaDataProxy:
    def __init__(self): ...
    @property
    def CppPointer(self) -> IntPtr: ...
    def Dispose(self) -> None: ...
    def SetContentInstanceId(self, uuid: Guid) -> None: ...


class PreviewBackground:
    def __init__(self, pPreviewBackground: IntPtr): ...
    @property
    def CppPointer(self) -> IntPtr: ...
    def EnvironmentInstanceId(self) -> Guid: ...
    def SetEnvironmentInstanceId(self, guid: Guid) -> None: ...
    def SetUpPreview(self, sceneServerPointer: IntPtr, guid: Guid) -> None: ...
    def ElementKind(self) -> str: ...


class PreviewGeometry:
    def __init__(self, pPreviewGeometry: IntPtr): ...
    @property
    def CppPointer(self) -> IntPtr: ...
    def SetUpPreview(self, sceneServerPointer: IntPtr, pRenderContent: IntPtr, bCopy: bool) -> None: ...
    def ElementKind(self) -> str: ...


class PreviewLighting:
    def __init__(self, pPreviewLighting: IntPtr): ...
    @property
    def CppPointer(self) -> IntPtr: ...
    def SetUpPreview(self, sceneServerPointer: IntPtr) -> None: ...
    def ElementKind(self) -> str: ...


class PreviewSceneQuality:
    #None = 0
    RealtimeQuick = 1
    Low = 1
    RefineFirstPass = 1
    RefineSecondPass = 2
    Medium = 2
    IntermediateProgressive = 3
    RefineThirdPass = 4
    Full = 4


class CreatePreviewReason:
    ContentChanged = 0
    ViewChanged = 1
    RefreshDisplay = 2
    UpdateBitmap = 3
    Other = 99


class CreatePreviewEventArgs:
    @property
    def PreviewNotifier(self) -> PreviewNotification: ...
    def SkipInitialisation(self) -> None: ...
    @property
    def Reason(self) -> CreatePreviewReason: ...
    @property
    def PreviewContent(self) -> RenderContent: ...
    @property
    def PreviewImageSize(self) -> Size: ...
    @property
    def Quality(self) -> PreviewSceneQuality: ...
    @property
    def PreviewImage(self) -> Bitmap: ...
    @PreviewImage.setter
    def PreviewImage(self, value: Bitmap) -> None: ...
    @property
    def Cancel(self) -> bool: ...
    @property
    def Id(self) -> int: ...
    @property
    def ContentKind(self) -> RenderContentKind: ...
    @property
    def ContentTypeId(self) -> Guid: ...
    @property
    def Environment(self) -> RenderEnvironment: ...
    @property
    def Objects(self) -> List: ...
    @property
    def Lights(self) -> List: ...
    @property
    def Viewport(self) -> ViewportInfo: ...


class CreateTexture2dPreviewEventArgs:
    @property
    def PreviewImageSize(self) -> Size: ...
    @property
    def PreviewImage(self) -> Bitmap: ...
    @PreviewImage.setter
    def PreviewImage(self, value: Bitmap) -> None: ...


class SceneServerDataUsage:
    Synchronous = 0
    Asynchronous = 1


class SceneServerData:
    def __init__(self, geo: PreviewGeometry, back: PreviewBackground, light: PreviewLighting, usage: SceneServerDataUsage): ...
    @property
    def CppPointer(self) -> IntPtr: ...
    def Dispose(self) -> None: ...


class PreviewSceneServer:
    def __init__(self, pPreviewSceneServer: IntPtr): ...
    @property
    def CppPointer(self) -> IntPtr: ...
    def Dispose(self) -> None: ...
    def ApplyRotation(self, X: float, Y: float, type: IRhRdkPreviewSceneServer_eRotationType) -> None: ...


class RenderPrimitive:
    def Dispose(self) -> None: ...
    @property
    def RhinoObject(self) -> RhinoObject: ...
    @property
    def PrimitiveType(self) -> RenderPrimitiveType: ...
    def Mesh(self) -> Mesh: ...
    def TryGetSphere(self) -> Tuple[bool, Sphere]: ...
    def TryGetBox(self) -> Tuple[bool, Box]: ...
    def TryGetPlane(self) -> Tuple[bool, PlaneSurface]: ...
    def TryGetCone(self) -> Tuple[bool, Cone, Plane]: ...
    @property
    def InstanceTransform(self) -> Transform: ...
    @property
    def RenderMaterial(self) -> RenderMaterial: ...
    @property
    def BoundingBox(self) -> BoundingBox: ...


class SupportOptions:
    def AlwaysShowSunPreview() -> bool: ...
    def SetAlwaysShowSunPreview(b: bool) -> None: ...
    def PreviewCustomRenderMeshes() -> bool: ...
    def SetPreviewCustomRenderMeshes(b: bool) -> None: ...
    def MultithreadedTextureEvaluation() -> bool: ...
    def SetMultithreadedTextureEvaluation(b: bool) -> None: ...
    def HarvestContentParameters() -> bool: ...
    def SetHarvestContentParameters(b: bool) -> None: ...
    def TextureSize() -> int: ...
    def SetTextureSize(size: RdkTextureSize, bSendEvent: bool) -> None: ...
    def SupportSharedUIsNoCache() -> bool: ...
    def SupportSharedUIs() -> bool: ...
    def SetSupportSharedUIs(b: bool) -> None: ...
    def CombineEditors() -> bool: ...
    def SetCombineEditors(b: bool) -> None: ...
    def UseDefaultLibraryPath() -> bool: ...
    def SetUseDefaultLibraryPath(b: bool) -> None: ...
    def CustomLibraryPath() -> str: ...
    def SetCustomLibraryPath(path: str) -> None: ...
    def ShowRenderContent() -> bool: ...
    def ShowDocuments() -> bool: ...
    def ShowCustom() -> bool: ...
    def SetShowRenderContent(b: bool) -> None: ...
    def SetShowDocuments(b: bool) -> None: ...
    def SetShowCustom(b: bool) -> None: ...
    def CustomPaths() -> str: ...
    def SetCustomPaths(path: str) -> None: ...
    def LibrariesInitialLocation() -> RdkInitialLocation: ...
    def SetLibrariesInitialLocation(l: RdkInitialLocation) -> None: ...
    def LibrariesInitialLocationCustomFolder() -> str: ...
    def SetLibrariesInitialLocationCustomFolder(path: str) -> None: ...
    def SetLastNavigatedLocation(folder: str) -> None: ...
    def LastNavigatedLocation() -> str: ...
    def PreferNativeRenderer() -> bool: ...
    def SetPreferNativeRenderer(b: bool) -> None: ...
    def UsePreviewCache() -> bool: ...
    def SetUsePreviewCache(b: bool) -> None: ...
    def UseQuickInitialPreview() -> bool: ...
    def SetUseQuickInitialPreview(b: bool) -> None: ...
    def UsePreview() -> bool: ...
    def UseRenderedPreview() -> bool: ...
    def ShowDetailsPanel() -> bool: ...
    def SetShowDetailsPanel(b: bool) -> None: ...
    def PreferredUnpackFolder() -> str: ...
    def SetPreferredUnpackFolder(path: str) -> None: ...
    def CheckSupportFilesBeforeRendering() -> bool: ...
    def SetCheckSupportFilesBeforeRendering(b: bool) -> None: ...
    def AutoSaveRenderings() -> bool: ...
    def SetAutoSaveRenderings(b: bool) -> None: ...
    def AutoSaveKeepAmount() -> int: ...
    def SetAutoSaveKeepAmount(value: int) -> None: ...
    def MaxPreviewCacheMB() -> int: ...
    def MaxPreviewSeconds() -> int: ...
    def EnablePreviewJobLog() -> bool: ...
    def DarkPreviewCheckerColor() -> int: ...
    def LightPreviewCheckerColor() -> int: ...
    def LabelFormatLoc() -> int: ...
    def SetLabelFormatLoc(value: int) -> None: ...
    def LabelFormatUtc() -> int: ...
    def SetLabelFormatUtc(value: int) -> None: ...


class RenderPlugInList:
    def __init__(self): ...


class RenderPlugInInfo:
    @property
    def Name(self) -> str: ...
    @Name.setter
    def Name(self, value: str) -> None: ...
    @property
    def PlugInId(self) -> Guid: ...
    @PlugInId.setter
    def PlugInId(self, value: Guid) -> None: ...


class RealtimeDisplayModeClassInfo:
    @property
    def Name(self) -> str: ...
    @property
    def GUID(self) -> Guid: ...
    @property
    def DrawOpenGl(self) -> bool: ...
    @property
    def RealtimeDisplayModeType(self) -> Type: ...
    @property
    def DontRegisterAttributesOnStart(self) -> bool: ...


class RealtimeDisplayMode:
    def add_HudStatusTextPressed(self, value: EventHandler) -> None: ...
    def remove_HudStatusTextPressed(self, value: EventHandler) -> None: ...
    def add_HudTimePressed(self, value: EventHandler) -> None: ...
    def remove_HudTimePressed(self, value: EventHandler) -> None: ...
    @property
    def Paused(self) -> bool: ...
    @Paused.setter
    def Paused(self, value: bool) -> None: ...
    @property
    def Locked(self) -> bool: ...
    @Locked.setter
    def Locked(self, value: bool) -> None: ...
    @property
    def MaxPasses(self) -> int: ...
    @MaxPasses.setter
    def MaxPasses(self, value: int) -> None: ...
    def add_MaxPassesChanged(self, value: EventHandler) -> None: ...
    def remove_MaxPassesChanged(self, value: EventHandler) -> None: ...
    @overload
    def RegisterDisplayModes(plugin: PlugIn) -> Set(RealtimeDisplayModeClassInfo): ...
    @overload
    def RegisterDisplayModes(assembly: Assembly, pluginId: Guid) -> Set(RealtimeDisplayModeClassInfo): ...
    @overload
    def UnregisterDisplayModes(plugin: PlugIn) -> None: ...
    @overload
    def UnregisterDisplayModes(assembly: Assembly, pluginId: Guid) -> None: ...
    def PostConstruct(self) -> None: ...
    def SignalRedraw(self) -> None: ...
    def ComputeViewportCrc(self, view: ViewInfo) -> UInt32: ...
    def SetView(self, view: ViewInfo) -> None: ...
    def GetView(self) -> ViewInfo: ...
    @property
    def LinearWorkflow(self) -> LinearWorkflow: ...
    def RemoveRealtimeViewport(realtimeViewport: IntPtr) -> None: ...
    @overload
    def GetRealtimeViewport(realtimeViewport: IntPtr) -> RealtimeDisplayMode: ...
    @overload
    def GetRealtimeViewport(realtimeViewport: IntPtr, create: bool) -> RealtimeDisplayMode: ...
    def CreateWorld(self, doc: RhinoDoc, viewInfo: ViewInfo, displayPipelineAttributes: DisplayPipelineAttributes) -> None: ...
    def GetRenderSize(self) -> Tuple[int, int]: ...
    def StartRenderer(self, w: int, h: int, doc: RhinoDoc, view: ViewInfo, viewportInfo: ViewportInfo, forCapture: bool, renderWindow: RenderWindow) -> bool: ...
    def ShutdownRenderer(self) -> None: ...
    def LastRenderedPass(self) -> int: ...
    def ShowCaptureProgress(self) -> bool: ...
    def CaptureProgress(self) -> float: ...
    def OnRenderSizeChanged(self, width: int, height: int) -> bool: ...
    def IsRendererStarted(self) -> bool: ...
    def IsFrameBufferAvailable(self, view: ViewInfo) -> bool: ...
    def IsCompleted(self) -> bool: ...
    def add_OnDisplayPipelineSettingsChanged(self, value: EventHandler) -> None: ...
    def remove_OnDisplayPipelineSettingsChanged(self, value: EventHandler) -> None: ...
    def add_OnInitFramebuffer(self, value: EventHandler) -> None: ...
    def remove_OnInitFramebuffer(self, value: EventHandler) -> None: ...
    def add_OnDrawMiddleground(self, value: EventHandler) -> None: ...
    def remove_OnDrawMiddleground(self, value: EventHandler) -> None: ...
    def DrawOpenGl(self) -> bool: ...
    def UseFastDraw(self) -> bool: ...
    def SetUseDrawOpenGl(self, use: bool) -> None: ...
    def OpenGlVersion(self) -> int: ...
    def HudProductName(self) -> str: ...
    def HudCustomStatusText(self) -> str: ...
    def HudMaximumPasses(self) -> int: ...
    def HudLastRenderedPass(self) -> int: ...
    def HudRendererPaused(self) -> bool: ...
    def HudRendererLocked(self) -> bool: ...
    def HudAllowEditMaxPasses(self) -> bool: ...
    def HudShowMaxPasses(self) -> bool: ...
    def HudShowPasses(self) -> bool: ...
    def HudShowCustomStatusText(self) -> bool: ...
    def HudShowControls(self) -> bool: ...
    def HudShow(self) -> bool: ...
    def HudStartTime(self) -> DateTime: ...
    def add_HudPlayButtonPressed(self, value: EventHandler) -> None: ...
    def remove_HudPlayButtonPressed(self, value: EventHandler) -> None: ...
    def add_HudPauseButtonPressed(self, value: EventHandler) -> None: ...
    def remove_HudPauseButtonPressed(self, value: EventHandler) -> None: ...
    def add_HudLockButtonPressed(self, value: EventHandler) -> None: ...
    def remove_HudLockButtonPressed(self, value: EventHandler) -> None: ...
    def add_HudUnlockButtonPressed(self, value: EventHandler) -> None: ...
    def remove_HudUnlockButtonPressed(self, value: EventHandler) -> None: ...
    def add_HudProductNamePressed(self, value: EventHandler) -> None: ...
    def remove_HudProductNamePressed(self, value: EventHandler) -> None: ...


class PixelBuffer:
    def __init__(self, bufferPointer: IntPtr): ...
    @property
    def Buffer(self) -> IntPtr: ...


class RenderWindowClonedEventArgs:
    @property
    def OldSessionId(self) -> Guid: ...
    @property
    def NewSessionId(self) -> Guid: ...
    @property
    def OldRenderWindow(self) -> RenderWindow: ...
    @property
    def NewRenderWindow(self) -> RenderWindow: ...


class RenderWindow:
    def Create(szSize: Size) -> RenderWindow: ...
    def Dispose(self) -> None: ...
    @property
    def SessionId(self) -> Guid: ...
    def add_Cloned(value: EventHandler) -> None: ...
    def remove_Cloned(value: EventHandler) -> None: ...
    def ChannelId(ch: StandardChannels) -> Guid: ...
    def Size(self) -> Size: ...
    def SetSize(self, size: Size) -> None: ...
    def SetView(self, view: ViewInfo) -> None: ...
    def SetProgress(self, text: str, progress: Single) -> None: ...
    def EndAsyncRender(self, successCode: RenderSuccessCode) -> None: ...
    def OpenChannel(self, id: StandardChannels) -> Channel: ...
    def GetBitmap(self) -> Bitmap: ...
    def AddWireframeChannel(self, doc: RhinoDoc, viewport: ViewportInfo, size: Size, region: Rectangle) -> bool: ...
    def AddChannel(self, channel: StandardChannels) -> bool: ...
    @overload
    def SetRGBAChannelColors(self, size: Size, colors: Set(Color4f)) -> None: ...
    @overload
    def SetRGBAChannelColors(self, rectangle: Rectangle, colors: Set(Color4f)) -> None: ...
    def Invalidate(self) -> None: ...
    def InvalidateArea(self, rect: Rectangle) -> None: ...
    def SaveDibAsBitmap(self, filename: str) -> None: ...
    @overload
    def SaveRenderImageAs(self, filename: str, renderEngineGuid: Guid, saveAlpha: bool) -> None: ...
    @overload
    def SaveRenderImageAs(self, filename: str, saveAlpha: bool) -> None: ...
    def FromSessionId(sessionId: Guid) -> RenderWindow: ...
    def GetAdjust(self) -> ImageAdjust: ...
    def SetAdjust(self, imageAdjust: ImageAdjust) -> None: ...


class RenderPanelType:
    RenderWindow = 0


class RenderTabs:
    def FromRenderSessionId(plugIn: PlugIn, tabType: Type, renderSessionId: Guid) -> Object: ...
    def SessionIdFromTab(tab: Object) -> Guid: ...
    def RegisterTab(self, plugin: PlugIn, tabType: Type, caption: str, icon: Icon) -> None: ...


class RenderPanels:
    def FromRenderSessionId(plugIn: PlugIn, panelType: Type, renderSessionId: Guid) -> Object: ...
    def RegisterPanel(self, plugin: PlugIn, renderPanelType: RenderPanelType, panelType: Type, caption: str, alwaysShow: bool, initialShow: bool) -> None: ...


class RenderPipeline:
    def SaveImage(self, fileName: str, saveAlpha: bool) -> bool: ...
    def CloseWindow(self) -> bool: ...
    def CommandResult(self) -> Result: ...
    def Render(self) -> RenderReturnCode: ...
    @property
    def RenderSessionId(self) -> Guid: ...
    def RenderWindow(self, view: RhinoView, rect: Rectangle, inWindow: bool) -> RenderReturnCode: ...
    @overload
    def RenderSize() -> Size: ...
    @overload
    def RenderSize(doc: RhinoDoc) -> Size: ...
    @overload
    def RenderSize(doc: RhinoDoc, fromRenderSources: bool) -> Size: ...
    def SetAsyncRenderContext(self, aRC: AsyncRenderContext) -> Tuple[AsyncRenderContext]: ...
    @overload
    def GetRenderWindow(self, withWireframeChannel: bool) -> RenderWindow: ...
    @overload
    def GetRenderWindow(self, withWireframeChannel: bool, fromRenderViewSource: bool) -> RenderWindow: ...
    @overload
    def GetRenderWindow(self) -> RenderWindow: ...
    def GetRenderWindowFromRenderViewSource(self, fromRenderViewSource: bool) -> RenderWindow: ...
    @ConfirmationSeconds.setter
    def ConfirmationSeconds(self, value: int) -> None: ...
    @property
    def PlugIn(self) -> PlugIn: ...
    def SupportsPause(self) -> bool: ...
    def PauseRendering(self) -> None: ...
    def ResumeRendering(self) -> None: ...
    def Dispose(self) -> None: ...


class RenderSourceView:
    def __init__(self, doc: RhinoDoc): ...
    def Dispose(self) -> None: ...
    def GetViewInfo(self) -> ViewInfo: ...


class AsyncRenderContext:
    @property
    def RenderWindow(self) -> RenderWindow: ...
    @RenderWindow.setter
    def RenderWindow(self, value: RenderWindow) -> None: ...
    @property
    def RenderThread(self) -> Thread: ...
    def StartRenderThread(self, threadStart: ThreadStart, threadName: str) -> bool: ...
    def JoinRenderThread(self) -> None: ...
    def StopRendering(self) -> None: ...
    def Dispose(self) -> None: ...


class RenderEndEventArgs:
    def __init__(self): ...


class SimulatedEnvironment:
    def __init__(self): ...
    @property
    def BackgroundColor(self) -> Color: ...
    @BackgroundColor.setter
    def BackgroundColor(self, value: Color) -> None: ...
    @property
    def BackgroundImage(self) -> SimulatedTexture: ...
    @BackgroundImage.setter
    def BackgroundImage(self, value: SimulatedTexture) -> None: ...
    @property
    def BackgroundProjection(self) -> BackgroundProjections: ...
    @BackgroundProjection.setter
    def BackgroundProjection(self, value: BackgroundProjections) -> None: ...
    def ProjectionFromString(projection: str) -> BackgroundProjections: ...
    def StringFromProjection(projection: BackgroundProjections) -> str: ...
    def Dispose(self) -> None: ...
    def ConstPointer(self) -> IntPtr: ...


class TextureProjectionMode:
    MappingChannel = 0
    View = 1
    Wcs = 2
    EnvironmentMap = 3
    WcsBox = 4
    Screen = 5


class TextureMode:
    PROJECTION_MODE = 0
    MAPPING_CHANNEL_MODE = 1
    WRAP_TYPE_MODE = 2
    REPEAT_LOCKED_MODE = 3
    OFFSET_LOCKED_MODE = 4
    PREVIEW_IN_3D_MODE = 5
    REPEAT_MODE = 6
    OFFSET_MODE = 7
    ROTATION_MODE = 8
    ENVIRONMENT_MAPPING_MODE = 9
    INTERNAL_ENVIRONMENT_MAPPING_MODE = 10
    PREVIEW_LOCAL_MAPPING_MODE = 11
    DISPLAY_IN_VIEWPORT_MODE = 12
    IS_HDR_CAPABLE_MODE = 13
    IS_LINEAR_MODE = 14
    IS_IMAGE_BASED = 15
    IS_NORMALMAP = 16


class TextureWrapType:
    Clamped = 0
    Repeating = 1


class TextureEnvironmentMappingMode:
    Automatic = 0
    Spherical = 1
    EnvironmentMap = 2
    Box = 3
    LightProbe = 5
    Cube = 6
    VerticalCrossCube = 7
    HorizontalCrossCube = 8
    Hemispherical = 9


class TextureGeneration:
    Allow = 1
    Disallow = 2


class TextureRenderHashFlags:
    ExcludeLocalMapping = 1


class RenderTexture(RenderContent):
    @overload
    def NewBitmapTexture(texture: SimulatedTexture) -> RenderTexture: ...
    @overload
    def NewBitmapTexture(texture: SimulatedTexture, doc: RhinoDoc) -> RenderTexture: ...
    def SaveAsImage(self, FullPath: str, width: int, height: int, depth: int) -> bool: ...
    @overload
    def NewBitmapTexture(bitmap: Bitmap, doc: RhinoDoc) -> RenderTexture: ...
    @property
    def RenderHashWithoutLocalMapping(self) -> UInt32: ...
    @property
    def LocalMappingTransform(self) -> Transform: ...
    def PixelSize(self) -> Tuple[int, int, int]: ...
    @overload
    def CreateEvaluator(self, evaluatorFlags: TextureEvaluatorFlags) -> TextureEvaluator: ...
    @overload
    def CreateEvaluator(self) -> TextureEvaluator: ...
    @overload
    def SimulateTexture(self, simulation: SimulatedTexture, isForDataOnly: bool) -> Tuple[SimulatedTexture]: ...
    @overload
    def SimulateTexture(self, simulation: SimulatedTexture, tg: TextureGeneration, size: int, obj: RhinoObject) -> Tuple[SimulatedTexture]: ...
    def SimulatedTexture(self, tg: TextureGeneration, size: int, obj: RhinoObject) -> SimulatedTexture: ...
    def GetProjectionMode(self) -> TextureProjectionMode: ...
    def SetProjectionMode(self, value: TextureProjectionMode, changeContext: ChangeContexts) -> None: ...
    def GetWrapType(self) -> TextureWrapType: ...
    def SetWrapType(self, value: TextureWrapType, changeContext: ChangeContexts) -> None: ...
    def GetMappingChannel(self) -> int: ...
    def SetMappingChannel(self, value: int, changeContext: ChangeContexts) -> None: ...
    def GetRepeatLocked(self) -> bool: ...
    def SetRepeatLocked(self, value: bool, changeContext: ChangeContexts) -> None: ...
    def GetOffsetLocked(self) -> bool: ...
    def SetOffsetLocked(self, value: bool, changeContext: ChangeContexts) -> None: ...
    def GetPreviewIn3D(self) -> bool: ...
    def SetPreviewIn3D(self, value: bool, changeContext: ChangeContexts) -> None: ...
    def GetRepeat(self) -> Vector3d: ...
    def SetRepeat(self, value: Vector3d, changeContext: ChangeContexts) -> None: ...
    def GetOffset(self) -> Vector3d: ...
    def SetOffset(self, value: Vector3d, changeContext: ChangeContexts) -> None: ...
    def GetRotation(self) -> Vector3d: ...
    def SetRotation(self, value: Vector3d, changeContext: ChangeContexts) -> None: ...
    def GetInternalEnvironmentMappingMode(self) -> TextureEnvironmentMappingMode: ...
    def GetEnvironmentMappingMode(self) -> TextureEnvironmentMappingMode: ...
    @overload
    def SetEnvironmentMappingMode(self, value: TextureEnvironmentMappingMode, changeContext: ChangeContexts) -> None: ...
    @overload
    def SetEnvironmentMappingMode(self, value: TextureEnvironmentMappingMode) -> None: ...
    def GetPreviewLocalMapping(self) -> bool: ...
    @overload
    def SetPreviewLocalMapping(self, value: bool, changeContext: ChangeContexts) -> None: ...
    def GetLocalMappingType(self) -> eLocalMappingType: ...
    @overload
    def SetPreviewLocalMapping(self, value: bool) -> None: ...
    def GetDisplayInViewport(self) -> bool: ...
    @overload
    def SetDisplayInViewport(self, value: bool, changeContext: ChangeContexts) -> None: ...
    @overload
    def SetDisplayInViewport(self, value: bool) -> None: ...
    def IsHdrCapable(self) -> bool: ...
    def IsLinear(self) -> bool: ...
    def IsNormalMap(self) -> bool: ...
    def GraphInfo(self, tgi: TextureGraphInfo) -> Tuple[TextureGraphInfo]: ...
    def SetGraphInfo(self, tgi: TextureGraphInfo) -> None: ...
    def IsImageBased(self) -> bool: ...
    def GetEnvironmentMappingProjection(mode: TextureEnvironmentMappingMode, reflectionVector: Vector3d) -> Tuple[bool, Single, Single]: ...
    def GetWcsBoxMapping(worldXyz: Point3d, normal: Vector3d) -> Point3d: ...


class TextureGraphInfo:
    def __init__(self): ...
    @property
    def CppPointer(self) -> IntPtr: ...
    def Dispose(self) -> None: ...
    def AmountU(self) -> float: ...
    def SetAmountU(self, d: float) -> None: ...
    def AmountV(self) -> float: ...
    def SetAmountV(self, d: float) -> None: ...
    def AmountW(self) -> float: ...
    def SetAmountW(self, d: float) -> None: ...
    def ActiveAxis(self) -> Axis: ...
    def SetActiveAxis(self, axis: Axis) -> None: ...
    def ActiveChannel(self) -> Channel: ...
    def SetActiveChannel(self, channel: Channel) -> None: ...


class TwoColorRenderTexture(RenderTexture):
    @property
    def Color1(self) -> Color4f: ...
    @Color1.setter
    def Color1(self, value: Color4f) -> None: ...
    @property
    def Color2(self) -> Color4f: ...
    @Color2.setter
    def Color2(self, value: Color4f) -> None: ...
    @property
    def Texture1On(self) -> bool: ...
    @Texture1On.setter
    def Texture1On(self, value: bool) -> None: ...
    @property
    def Texture2On(self) -> bool: ...
    @Texture2On.setter
    def Texture2On(self, value: bool) -> None: ...
    @property
    def Texture1Amount(self) -> float: ...
    @Texture1Amount.setter
    def Texture1Amount(self, value: float) -> None: ...
    @property
    def Texture2Amount(self) -> float: ...
    @Texture2Amount.setter
    def Texture2Amount(self, value: float) -> None: ...
    @property
    def SwapColors(self) -> bool: ...
    @SwapColors.setter
    def SwapColors(self, value: bool) -> None: ...
    @property
    def SuperSample(self) -> bool: ...
    @SuperSample.setter
    def SuperSample(self, value: bool) -> None: ...


class TextureEvaluator:
    def Initialize(self) -> bool: ...
    def GetColor(self, uvw: Point3d, duvwdx: Vector3d, duvwdy: Vector3d) -> Color4f: ...
    def Dispose(self) -> None: ...


class TimeZone:
    @property
    def Name(self) -> str: ...
    @property
    def Hours(self) -> float: ...
    @property
    def Longitude(self) -> float: ...
    @property
    def Latitude(self) -> float: ...
    def TimeZones() -> int: ...
    def TimeZoneAt(index: int) -> TimeZone: ...


class ContentUndoHelper:
    def __init__(self, doc: RhinoDoc, description: str): ...
    def AddContent(self, content: RenderContent, parent: RenderContent) -> bool: ...
    def ModifyContent(self, content: RenderContent) -> bool: ...
    def TweakContent(self, content: RenderContent, parameterName: str) -> bool: ...
    def Dispose(self) -> None: ...


class ContentUndoBlocker:
    def __init__(self): ...
    def Dispose(self) -> None: ...


class RdkUndoRecord:
    def __init__(self, pUndoRecord: IntPtr): ...
    def Dispose(self) -> None: ...
    def SetDescription(self, description: str) -> None: ...


class RdkUndo:
    def __init__(self, pUndoRecord: IntPtr): ...
    def Dispose(self) -> None: ...
    def NewUndoRecord(self) -> RdkUndoRecord: ...


class NamedValue:
    def __init__(self, name: str, value: Object): ...
    @property
    def Name(self) -> str: ...
    @Name.setter
    def Name(self, value: str) -> None: ...
    @property
    def Value(self) -> Object: ...
    @Value.setter
    def Value(self, value: Object) -> None: ...


class ConvertibleExtensions:
    def ToColor4f(variant: IConvertible) -> Color4f: ...
    def ToVector2d(variant: IConvertible) -> Vector2d: ...
    def ToVector3d(variant: IConvertible) -> Vector3d: ...


class SimulatedTexture:
    def __init__(self): ...
    @property
    def BitmapSize() -> int: ...
    @BitmapSize.setter
    def BitmapSize(value: int) -> None: ...
    @property
    def LocalMappingTransform(self) -> Transform: ...
    @property
    def Filename(self) -> str: ...
    @Filename.setter
    def Filename(self, value: str) -> None: ...
    @property
    def OriginalFilename(self) -> str: ...
    @property
    def Repeat(self) -> Vector2d: ...
    @Repeat.setter
    def Repeat(self, value: Vector2d) -> None: ...
    @property
    def Offset(self) -> Vector2d: ...
    @Offset.setter
    def Offset(self, value: Vector2d) -> None: ...
    @property
    def Rotation(self) -> float: ...
    @Rotation.setter
    def Rotation(self, value: float) -> None: ...
    @property
    def Repeating(self) -> bool: ...
    @Repeating.setter
    def Repeating(self, value: bool) -> None: ...
    @property
    def MappingChannel(self) -> int: ...
    @MappingChannel.setter
    def MappingChannel(self, value: int) -> None: ...
    @property
    def ProjectionMode(self) -> ProjectionModes: ...
    @ProjectionMode.setter
    def ProjectionMode(self, value: ProjectionModes) -> None: ...
    def SetMappingChannelAndProjectionMode(self, pm: ProjectionModes, mappingChannel: int, emm: EnvironmentMappingModes) -> None: ...
    @property
    def HasTransparentColor(self) -> bool: ...
    @HasTransparentColor.setter
    def HasTransparentColor(self, value: bool) -> None: ...
    @property
    def TransparentColor(self) -> Color4f: ...
    @TransparentColor.setter
    def TransparentColor(self, value: Color4f) -> None: ...
    @property
    def TransparentColorSensitivity(self) -> float: ...
    @TransparentColorSensitivity.setter
    def TransparentColorSensitivity(self, value: float) -> None: ...
    @property
    def Filtered(self) -> bool: ...
    @Filtered.setter
    def Filtered(self, value: bool) -> None: ...
    @overload
    def UnitsToMeters(self, units: float) -> float: ...
    @overload
    def UnitsToMeters(self, doc: RhinoDoc, units: float) -> float: ...
    @overload
    def MetersToUnits(self, units: float) -> float: ...
    @overload
    def MetersToUnits(self, doc: RhinoDoc, units: float) -> float: ...
    def Texture(self) -> Texture: ...
    def Dispose(self) -> None: ...
    def ConstPointer(self) -> IntPtr: ...


class UndoRedo:
    def add_UndoRedoChanged(value: EventHandler) -> None: ...
    def remove_UndoRedoChanged(value: EventHandler) -> None: ...


class Sun(DocumentOrFreeFloatingBase):
    def __init__(self): ...
    def add_Changed(value: EventHandler) -> None: ...
    def remove_Changed(value: EventHandler) -> None: ...
    def SunDirection(latitude: float, longitude: float, when: DateTime) -> Vector3d: ...
    def Dispose(self) -> None: ...
    @property
    def Enabled(self) -> bool: ...
    @Enabled.setter
    def Enabled(self, value: bool) -> None: ...
    @property
    def ManualControl(self) -> bool: ...
    @ManualControl.setter
    def ManualControl(self, value: bool) -> None: ...
    @property
    def SkylightOn(self) -> bool: ...
    @SkylightOn.setter
    def SkylightOn(self, value: bool) -> None: ...
    @property
    def DaylightSaving(self) -> bool: ...
    @DaylightSaving.setter
    def DaylightSaving(self, value: bool) -> None: ...
    @property
    def DaylightSavingMinutes(self) -> int: ...
    @DaylightSavingMinutes.setter
    def DaylightSavingMinutes(self, value: int) -> None: ...
    @property
    def TimeZone(self) -> float: ...
    @TimeZone.setter
    def TimeZone(self, value: float) -> None: ...
    @property
    def North(self) -> float: ...
    @North.setter
    def North(self, value: float) -> None: ...
    @property
    def Vector(self) -> Vector3d: ...
    @property
    def Light(self) -> Light: ...
    @overload
    def SetPosition(self, azimuthDegrees: float, altitudeDegrees: float) -> None: ...
    @overload
    def SetPosition(self, when: DateTime, latitudeDegrees: float, longitudeDegrees: float) -> None: ...
    @property
    def Azimuth(self) -> float: ...
    @property
    def Altitude(self) -> float: ...
    @property
    def Latitude(self) -> float: ...
    @property
    def Longitude(self) -> float: ...
    def GetDateTime(self, kind: DateTimeKind) -> DateTime: ...
    def SetDateTime(self, time: DateTime, kind: DateTimeKind) -> None: ...
    def ShowDialog(self) -> None: ...
    def ColorFromAltitude(altitudeDegrees: float) -> Color: ...
    def AltitudeFromValues(latitude: float, longitude: float, timezoneHours: float, daylightMinutes: int, when: DateTime, hours: float, fast: bool) -> float: ...
    def JulianDay(timezoneHours: float, daylightMinutes: int, when: DateTime, hours: float) -> float: ...
    def TwilightZone() -> float: ...
    def Here() -> Tuple[bool, float, float]: ...
    def CopyFrom(self, src: FreeFloatingBase) -> None: ...


class Skylight(DocumentOrFreeFloatingBase):
    @overload
    def __init__(self): ...
    @overload
    def __init__(self, src: Skylight): ...
    def CopyFrom(self, src: FreeFloatingBase) -> None: ...
    def add_Changed(value: EventHandler) -> None: ...
    def remove_Changed(value: EventHandler) -> None: ...
    @property
    def Enabled(self) -> bool: ...
    @Enabled.setter
    def Enabled(self, value: bool) -> None: ...
    @property
    def ShadowIntensity(self) -> float: ...
    @ShadowIntensity.setter
    def ShadowIntensity(self, value: float) -> None: ...
    @property
    def CustomEnvironmentOn(self) -> bool: ...
    @CustomEnvironmentOn.setter
    def CustomEnvironmentOn(self, value: bool) -> None: ...
    @property
    def CustomEnvironment(self) -> Guid: ...
    @CustomEnvironment.setter
    def CustomEnvironment(self, value: Guid) -> None: ...


class ImageFileEventArgs:
    @property
    def Event(self) -> ImageFileEvent: ...
    @property
    def FileName(self) -> str: ...
    @property
    def RenderEngine(self) -> str: ...
    @property
    def RenderEngineId(self) -> Guid: ...
    @property
    def SessionId(self) -> Guid: ...
    @property
    def EllapsedTime(self) -> int: ...


class ImageFileEvent:
    Saved = 0
    Loaded = 1
    Deleted = 2


class ImageFile:
    def add_Saved(value: EventHandler) -> None: ...
    def remove_Saved(value: EventHandler) -> None: ...
    def add_Loaded(value: EventHandler) -> None: ...
    def remove_Loaded(value: EventHandler) -> None: ...
    def add_Deleted(value: EventHandler) -> None: ...
    def remove_Deleted(value: EventHandler) -> None: ...


class RenderContentManager:
    @property
    def UserRenderContentPath() -> str: ...
    def RestoreRenderContent() -> bool: ...


class Methods:
    #None = 0
    FloydSteinberg = 1
    SimpleNoise = 2


class RenderingSources:
    ActiveViewport = 0
    SpecificViewport = 1
    NamedView = 2
    SnapShot = 3


class ShowContentChooserFlags:
    #None = 0
    HideNewTab = 1
    HideExistingTab = 2


class MatchDataResult:
    #None = 0
    Some = 1
    All = 2


class ExtraRequirementsSetContexts:
    UI = 0
    Drop = 1
    Program = 2


class ChangeContexts:
    UI = 0
    Drop = 1
    Program = 2
    Ignore = 3
    Tree = 4
    Undo = 5
    FieldInit = 6
    Serialize = 7


class Usage:
    #None = 0
    Background = 1
    ReflectionAndRefraction = 2
    Skylighting = 4
    AnyUsage = 7


class UiFrameworks:
    Win32 = 0
    Cocoa = 1
    Eto = 2
    WinForms = 3
    WPF = 4


class ShowContentChooserResults:
    #None = 0
    New = 1
    Copy = 2
    Instance = 3


class StandardChildSlots:
    #None = 0
    Diffuse = 1
    PbrBaseColor = 1
    Transparency = 2
    PbrOpacity = 2
    Bump = 4
    Environment = 8
    PbrSubsurface = 32
    PbrSubSurfaceScattering = 64
    PbrSubsurfaceScatteringRadius = 128
    PbrMetallic = 256
    PbrSpecular = 512
    PbrSpecularTint = 1024
    PbrRoughness = 2048
    PbrAnisotropic = 4096
    PbrAnisotropicRotation = 8192
    PbrSheen = 16384
    PbrSheenTint = 32768
    PbrClearcoat = 65536
    PbrClearcoatRoughness = 131072
    PbrOpacityIor = 262144
    PbrOpacityRoughness = 524288
    PbrEmission = 1048576
    PbrAmbientOcclusion = 2097152
    PbrDisplacement = 8388608
    PbrClearcoatBump = 16777216


class PhysicallyBased:
    def __init__(self): ...


class BasicMaterialParameterNames:
    def __init__(self): ...


class PreviewGeometryType:
    Sphere = 0
    Cube = 1
    Cone = 2
    Pyramid = 3
    Torus = 4
    Plane = 5


class PreviewBackgroundType:
    #None = 1
    Checkered = 2


class ParametersNames:
    def __init__(self): ...
    @property
    def BaseColor() -> str: ...
    @property
    def BRDF() -> str: ...
    @property
    def Subsurface() -> str: ...
    @property
    def SubsurfaceScatteringColor() -> str: ...
    @property
    def SubsurfaceScatteringRadius() -> str: ...
    @property
    def Specular() -> str: ...
    @property
    def SpecularTint() -> str: ...
    @property
    def Metallic() -> str: ...
    @property
    def Roughness() -> str: ...
    @property
    def Anisotropic() -> str: ...
    @property
    def AnisotropicRotation() -> str: ...
    @property
    def Sheen() -> str: ...
    @property
    def SheenTint() -> str: ...
    @property
    def Clearcoat() -> str: ...
    @property
    def ClearcoatRoughness() -> str: ...
    @property
    def ClearcoatBump() -> str: ...
    @property
    def OpacityIor() -> str: ...
    @property
    def Opacity() -> str: ...
    @property
    def OpacityRoughness() -> str: ...
    @property
    def Emission() -> str: ...
    @property
    def Smudge() -> str: ...
    @property
    def Normal() -> str: ...
    @property
    def Displacement() -> str: ...
    @property
    def Bump() -> str: ...
    @property
    def AmbientOcclusion() -> str: ...
    def FromTextureType(tt: TextureType) -> str: ...


class BRDFs:
    GGX = 0
    Ward = 1


class SceneObject:
    @property
    def Mesh(self) -> Mesh: ...
    @property
    def Material(self) -> RenderMaterial: ...


class RdkTextureSize:
    Size1 = 128
    Size2 = 256
    Size3 = 512
    Size4 = 1024
    Size5 = 2048


class RdkInitialLocation:
    RenderContent = 0
    LastOpenedFolder = 1
    CustomFolder = 2


class DisplayPipelineSettingsChangedEventArgs:
    def __init__(self, dpa: DisplayPipelineAttributes): ...
    @property
    def Attributes(self) -> DisplayPipelineAttributes: ...


class InitFramebufferEventArgs:
    def __init__(self, dp: DisplayPipeline): ...
    @property
    def Pipeline(self) -> DisplayPipeline: ...


class DrawMiddlegroundEventArgs:
    def __init__(self, dp: DisplayPipeline): ...
    @property
    def Pipeline(self) -> DisplayPipeline: ...


class HudMaxPassesChangedEventArgs:
    def __init__(self, mp: int): ...
    @property
    def MaxPasses(self) -> int: ...


class RenderSuccessCode:
    Completed = 0
    Failed = 1


class StandardChannels:
    #None = 0
    Red = 1
    Green = 2
    Blue = 4
    Alpha = 8
    RGBA = 14
    RGB = 15
    DistanceFromCamera = 16
    NormalX = 32
    NormalY = 64
    NormalZ = 128
    LuminanceRed = 256
    LuminanceGreen = 512
    LuminanceBlue = 1024
    BackgroundLuminanceRed = 4096
    BackgroundLuminanceGreen = 8192
    BackgroundLuminanceBlue = 16384
    MaterialIds = 65536
    ObjectIds = 131072
    Wireframe = 262144


class Channel:
    def PixelSize(self) -> int: ...
    @overload
    def SetValue(self, x: int, y: int, value: Single) -> None: ...
    def SetValues(self, rectangle: Rectangle, bufferResolution: Size, colorBuffer: PixelBuffer) -> None: ...
    @overload
    def SetValue(self, x: int, y: int, value: Color4f) -> None: ...
    def AddValue(self, x: int, y: int, value: Color4f) -> None: ...
    def Dispose(self) -> None: ...


class ImageAdjust:
    @property
    def Gamma(self) -> Single: ...
    @Gamma.setter
    def Gamma(self, value: Single) -> None: ...
    @property
    def Dither(self) -> Methods: ...
    @Dither.setter
    def Dither(self, value: Methods) -> None: ...


class RenderReturnCode:
    Ok = 0
    EmptyScene = 1
    Cancel = 2
    NoActiveView = 3
    OnPreCreateWindow = 4
    NoFrameWndPointer = 5
    ErrorCreatingWindow = 6
    ErrorStartingRender = 7
    EnterModalLoop = 8
    ExitModalLoop = 9
    ExitRhino = 10
    InternalError = 11


class BackgroundProjections:
    Planar = 0
    Spherical = 1
    Emap = 2
    Box = 3
    Automatic = 4
    Lightprobe = 5
    Cubemap = 6
    VerticalCrossCubemap = 7
    HorizontalCrossCubemap = 8


class TextureEvaluatorFlags:
    Normal = 0
    DisableFiltering = 1
    DisableLocalMapping = 2
    DisableAdjustment = 4
    DisableProjectionChange = 8


class eLocalMappingType:
    lmt_none = 0
    lmt_2D = 1
    lmt_3D = 2
    lmt_force32bit = 4294967295


class TextureGeneration:
    Allow = 1
    Disallow = 2


class Axis:
    kU = 0
    kV = 1
    kW = 2


class Channel:
    kRed = 0
    kGrn = 1
    kBlu = 2
    kAlp = 3
    kLum = 4


class ProjectionModes:
    MappingChannel = 0
    View = 1
    Wcs = 2
    Emap = 3
    WcsBox = 4
    Screen = 5


class EnvironmentMappingModes:
    Automatic = 0
    Spherical = 1
    Emap = 2
    Box = 3
    Lightprobe = 5
    Cubemap = 6
    VerticalCrossCubemap = 7
    HorizontalCrossCubemap = 8
    Hemispherical = 9


class ParametersNames:
    def __init__(self): ...
    @property
    def BaseColor() -> str: ...
    @property
    def BRDF() -> str: ...
    @property
    def Subsurface() -> str: ...
    @property
    def SubsurfaceScatteringColor() -> str: ...
    @property
    def SubsurfaceScatteringRadius() -> str: ...
    @property
    def Specular() -> str: ...
    @property
    def SpecularTint() -> str: ...
    @property
    def Metallic() -> str: ...
    @property
    def Roughness() -> str: ...
    @property
    def Anisotropic() -> str: ...
    @property
    def AnisotropicRotation() -> str: ...
    @property
    def Sheen() -> str: ...
    @property
    def SheenTint() -> str: ...
    @property
    def Clearcoat() -> str: ...
    @property
    def ClearcoatRoughness() -> str: ...
    @property
    def ClearcoatBump() -> str: ...
    @property
    def OpacityIor() -> str: ...
    @property
    def Opacity() -> str: ...
    @property
    def OpacityRoughness() -> str: ...
    @property
    def Emission() -> str: ...


class ChildSlotNames:
    def __init__(self): ...
    @property
    def BaseColor() -> str: ...
    @property
    def Subsurface() -> str: ...
    @property
    def SubsurfaceScatteringColor() -> str: ...
    @property
    def SubsurfaceScatteringRadius() -> str: ...
    @property
    def Specular() -> str: ...
    @property
    def SpecularTint() -> str: ...
    @property
    def Metallic() -> str: ...
    @property
    def Roughness() -> str: ...
    @property
    def Anisotropic() -> str: ...
    @property
    def AnisotropicRotation() -> str: ...
    @property
    def Sheen() -> str: ...
    @property
    def SheenTint() -> str: ...
    @property
    def Clearcoat() -> str: ...
    @property
    def ClearcoatRoughness() -> str: ...
    @property
    def ClearcoatBump() -> str: ...
    @property
    def OpacityIor() -> str: ...
    @property
    def Opacity() -> str: ...
    @property
    def OpacityRoughness() -> str: ...
    @property
    def Emission() -> str: ...
    @property
    def Displacement() -> str: ...
    @property
    def Bump() -> str: ...
    @property
    def AmbientOcclusion() -> str: ...
    def FromTextureType(tt: TextureType) -> str: ...
