from typing import Tuple, Set, Iterable, List

class Solver:
    def Compute (nodes : Node2List, hull : List) -> bool: ...
    def ComputeHull (GH_pts : Iterable[GH_Point]) -> Polyline: ...
    def ComputeHull (GH_pts : Iterable[GH_Point], plane : Plane) -> Tuple[Polyline, Plane]: ...
    def ComputeHull (pts : Node2List) -> Polyline: ...
