from typing import Tuple, Set, Iterable, List

class GH_GenericLayout:
    def Vertical_ByIndex (area : Rectangle, stack : List, expand : bool) -> List: ...
    def Horizontal_ByIndex (area : Rectangle, stack : List, expand : bool) -> List: ...
    def Vertical_ByPosition (area : Rectangle, stack : List, expand : bool) -> List: ...
    def Vertical_ByPosition (area : Rectangle, stack : List, expand : bool, radical : int) -> List: ...
    def Horizontal_ByPosition (area : Rectangle, stack : List, expand : bool) -> List: ...
    def Horizontal_ByPosition (area : Rectangle, stack : List, expand : bool, radical : int) -> List: ...
